type ProblemExample = { input: string; output: string; explanation?: string }
type ProblemSeed = {
  patternSlug: string
  title: string
  prompt: string
  constraints: string
  examples: ProblemExample[]
  difficulty: 'easy' | 'medium' | 'hard'
  estMin: number
  tags: string[]
  hints: string[]
}
export const PROBLEMS_BATCH_9: ProblemSeed[] = [
  {
    patternSlug: 'two-pointers',
    title: 'The Polar Sum Locator',
    prompt: 'Given a **sorted** array `nums` and integer `target`, find two distinct indices `i < j` such that `nums[i] + nums[j] == target`. Return `[i+1, j+1]` (1-indexed) or `[-1, -1]` if none exist.',
    constraints: '2 ≤ nums.length ≤ 10^5\n-10^9 ≤ nums[i] ≤ 10^9\nArray is sorted in non-decreasing order',
    examples: [
      { input: 'nums = [1,4,7,11,15], target = 18', output: '[3,4]', explanation: 'nums[2]+nums[3] = 7+11 = 18' },
      { input: 'nums = [2,3,6,8], target = 5', output: '[1,2]' },
    ],
    difficulty: 'easy',
    estMin: 10,
    tags: ['two-pointers', 'sorted-array'],
    hints: ['Start with left=0 and right=n-1.', 'If sum > target, decrement right. If sum < target, increment left.', 'Stop when pointers meet.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Minimum Gap Pair',
    prompt: 'Given a **sorted** array `nums`, find the pair of elements `(a, b)` where `a != b` whose absolute difference is **minimized**. Return `[a, b]`. If multiple pairs have the same minimum difference, return the one with the smallest `a`.',
    constraints: '2 ≤ nums.length ≤ 10^5\n-10^9 ≤ nums[i] ≤ 10^9',
    examples: [
      { input: 'nums = [1,5,6,10,14]', output: '[5,6]', explanation: 'diff = 1, smallest possible' },
      { input: 'nums = [3,8,15]', output: '[3,8]', explanation: 'diff 5 < 7' },
    ],
    difficulty: 'easy',
    estMin: 10,
    tags: ['two-pointers', 'sorted-array'],
    hints: ['Adjacent elements in a sorted array have the smallest possible differences.', 'Scan adjacent pairs with a single pointer.', 'Track the minimum diff seen so far.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Triangle Triplet Counter',
    prompt: 'Given an array `sides` of positive integers, count how many triplets `(i, j, k)` with `i < j < k` form a **valid triangle** (sum of any two sides > third side). Return the count.',
    constraints: '3 ≤ sides.length ≤ 1000\n1 ≤ sides[i] ≤ 10^4',
    examples: [
      { input: 'sides = [2,3,4,5]', output: '4', explanation: '(2,3,4),(2,4,5),(3,4,5),(2,3,5) all valid' },
      { input: 'sides = [1,1,1,2]', output: '4' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['two-pointers', 'sorting', 'counting'],
    hints: ['Sort the array first.', 'Fix the largest side k, then use two pointers on [0..k-1].', 'If sides[l]+sides[r] > sides[k], all elements from l to r-1 also work.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Capsule Range Scanner',
    prompt: 'Given a **sorted** array `nums` and integer `k`, count the number of pairs `(i, j)` with `i < j` such that `nums[j] - nums[i] <= k`. Return the count.',
    constraints: '2 ≤ nums.length ≤ 10^5\n0 ≤ nums[i] ≤ 10^9\n0 ≤ k ≤ 10^9',
    examples: [
      { input: 'nums = [1,3,5,7], k = 4', output: '5', explanation: 'pairs (1,3),(1,5),(3,5),(3,7),(5,7) all within range 4' },
      { input: 'nums = [2,5,9], k = 2', output: '0' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['two-pointers', 'sorted-array', 'counting'],
    hints: ['Fix the right pointer j, slide i from right.', 'For each j, find smallest i where nums[j]-nums[i] <= k.', 'All positions between that i and j-1 form valid pairs.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Quadruplet Mission',
    prompt: 'Given an integer array `nums` and target `t`, return **all unique quadruplets** `[a,b,c,d]` such that `a+b+c+d == t`. No duplicate quadruplets.',
    constraints: '4 ≤ nums.length ≤ 200\n-10^9 ≤ nums[i] ≤ 10^9',
    examples: [
      { input: 'nums = [1,0,-1,0,-2,2], t = 0', output: '[[-2,-1,1,2],[-2,0,0,2],[-1,0,0,1]]' },
      { input: 'nums = [2,2,2,2,2], t = 8', output: '[[2,2,2,2]]' },
    ],
    difficulty: 'medium',
    estMin: 25,
    tags: ['two-pointers', 'sorting', 'deduplication'],
    hints: ['Sort and fix two outer indices, use two pointers for the inner pair.', 'Skip duplicates at each level.', 'Outer loops: O(n^2), inner two-pointer: O(n) → O(n^3) total.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Zero-Sum Triplet Finder',
    prompt: 'Given integer array `nums`, find all **unique triplets** `[a,b,c]` summing to **zero**. No duplicate triplets in output.',
    constraints: '3 ≤ nums.length ≤ 3000\n-10^5 ≤ nums[i] ≤ 10^5',
    examples: [
      { input: 'nums = [-4,-1,-1,0,1,2]', output: '[[-1,-1,2],[-1,0,1]]' },
      { input: 'nums = [0,0,0,0]', output: '[[0,0,0]]' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['two-pointers', 'sorting'],
    hints: ['Sort first, then fix one element and use two pointers for the rest.', 'Skip duplicates: if nums[i]==nums[i-1] continue.', 'After finding a triplet, advance both pointers and skip duplicates.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Closest Triplet Approximator',
    prompt: 'Given integer array `nums` and integer `target`, find the triplet `(a,b,c)` whose sum is **closest to target**. Return that sum. If tie, return the smaller sum.',
    constraints: '3 ≤ nums.length ≤ 500\n-10^4 ≤ nums[i] ≤ 10^4',
    examples: [
      { input: 'nums = [-1,2,1,-4], target = 1', output: '2', explanation: '-1+2+1=2, closest to 1' },
      { input: 'nums = [0,0,0], target = 1', output: '0' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['two-pointers', 'sorting'],
    hints: ['Sort and fix the first element, use two pointers for the rest.', 'Track the sum with minimum |sum - target|.', 'Steer pointers based on whether current sum is above or below target.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Fluid Reservoir Optimizer',
    prompt: 'You have `n` vertical walls at positions `1..n` with heights `h[i]`. Two walls form a container. Find the pair of walls that holds the **maximum volume of fluid** (width × min height). Return that volume.',
    constraints: '2 ≤ h.length ≤ 10^5\n1 ≤ h[i] ≤ 10^4',
    examples: [
      { input: 'h = [1,8,6,2,5,4,8,3,7]', output: '49', explanation: 'walls at index 1 and 8: min(8,7)*7=49' },
      { input: 'h = [1,1]', output: '1' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['two-pointers', 'greedy'],
    hints: ['Start with the widest container (left=0, right=n-1).', 'Moving the taller wall inward can only decrease volume.', 'Always move the pointer at the shorter wall.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Sorted Merge Operative',
    prompt: 'Given two **sorted** arrays `a` (length `m`) and `b` (length `n`), merge them into a single sorted array **in-place** into `a` which has extra space for `n` elements. Do not use extra arrays.',
    constraints: '0 ≤ m, n ≤ 2×10^5\na.length == m + n\nBoth arrays sorted non-decreasingly',
    examples: [
      { input: 'a = [1,3,5,0,0,0], m = 3, b = [2,4,6], n = 3', output: '[1,2,3,4,5,6]' },
      { input: 'a = [1], m = 1, b = [], n = 0', output: '[1]' },
    ],
    difficulty: 'easy',
    estMin: 10,
    tags: ['two-pointers', 'in-place', 'sorting'],
    hints: ['Fill from the back of array a.', 'Use three pointers: i=m-1, j=n-1, k=m+n-1.', 'Place the larger of a[i] and b[j] at position k.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Subarray Squeezer',
    prompt: 'Given a **sorted** array `nums` and integer `target`, find the **smallest** contiguous subarray whose sum equals `target`. Return its length, or `-1` if none exists.',
    constraints: '1 ≤ nums.length ≤ 10^5\n1 ≤ nums[i] ≤ 10^4\n1 ≤ target ≤ 10^9',
    examples: [
      { input: 'nums = [1,2,3,4,5], target = 9', output: '2', explanation: '[4,5] sums to 9' },
      { input: 'nums = [1,1,1,1], target = 5', output: '-1' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['two-pointers', 'sliding-window'],
    hints: ['Use two pointers left and right; expand right to grow sum, shrink left to reduce.', 'When sum == target, record length and try shrinking.', 'Since all values positive, this converges.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Vowel Swap Cipher',
    prompt: 'Given string `s`, reverse **only the vowels** (`a,e,i,o,u`, case-insensitive) while keeping all other characters in place. Return the result.',
    constraints: '1 ≤ s.length ≤ 3×10^5\ns contains printable ASCII',
    examples: [
      { input: 's = "hello"', output: '"holle"' },
      { input: 's = "leetcode"', output: '"leotcede"' },
    ],
    difficulty: 'easy',
    estMin: 10,
    tags: ['two-pointers', 'string'],
    hints: ['Use two pointers from both ends.', 'Advance each pointer until it lands on a vowel.', 'Swap vowels and move both pointers inward.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Non-Alpha Palindrome Check',
    prompt: 'A string is a **filtered palindrome** if it reads the same forwards and backwards when only alphanumeric characters are considered (case-insensitive). Given string `s`, return `true` if it qualifies.',
    constraints: '1 ≤ s.length ≤ 2×10^5',
    examples: [
      { input: 's = "A man, a plan, a canal: Panama"', output: 'true' },
      { input: 's = "race a car"', output: 'false' },
    ],
    difficulty: 'easy',
    estMin: 10,
    tags: ['two-pointers', 'string'],
    hints: ['Use left/right pointers, skip non-alphanumeric on both sides.', 'Compare lowercased characters at each step.', 'Stop when pointers cross.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Duplicate Compactor',
    prompt: 'Given a **sorted** array `nums`, remove duplicates **in-place** so each value appears **at most twice**. Return the new length `k`. The first `k` elements of `nums` should hold the result.',
    constraints: '1 ≤ nums.length ≤ 3×10^4\n-10^4 ≤ nums[i] ≤ 10^4',
    examples: [
      { input: 'nums = [1,1,1,2,2,3]', output: '5, nums = [1,1,2,2,3,...]' },
      { input: 'nums = [0,0,1,1,1,1,2,3,3]', output: '7' },
    ],
    difficulty: 'easy',
    estMin: 12,
    tags: ['two-pointers', 'in-place'],
    hints: ['Maintain a write pointer w starting at 2.', 'For each read position r >= 2, if nums[r] != nums[w-2], copy it.', 'Generalizes to "at most k occurrences".'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Color Sort Commander',
    prompt: 'Given array `colors` where each element is `0`, `1`, or `2`, sort it **in-place** in O(n) time using constant extra space so all `0`s come first, then `1`s, then `2`s.',
    constraints: '1 ≤ colors.length ≤ 3×10^4\ncolors[i] ∈ {0, 1, 2}',
    examples: [
      { input: 'colors = [2,0,2,1,1,0]', output: '[0,0,1,1,2,2]' },
      { input: 'colors = [2,0,1]', output: '[0,1,2]' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['two-pointers', 'sorting', 'dutch-flag'],
    hints: ['Use the Dutch National Flag algorithm with 3 pointers: low, mid, high.', 'Invariant: [0..low-1]=0, [low..mid-1]=1, [high+1..n-1]=2.', 'Process mid pointer: if 0 swap with low, if 2 swap with high.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Zero Exile Protocol',
    prompt: 'Given integer array `nums`, move all `0`s to the **end** while preserving the **relative order** of non-zero elements. Do this **in-place** without extra arrays.',
    constraints: '1 ≤ nums.length ≤ 10^4\n-2^31 ≤ nums[i] ≤ 2^31-1',
    examples: [
      { input: 'nums = [0,1,0,3,12]', output: '[1,3,12,0,0]' },
      { input: 'nums = [0,0,1]', output: '[1,0,0]' },
    ],
    difficulty: 'easy',
    estMin: 10,
    tags: ['two-pointers', 'in-place'],
    hints: ['Use a slow pointer that marks the next non-zero write position.', 'Iterate with a fast pointer; when non-zero found, write at slow position.', 'Fill remaining positions with 0.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Value Purge Operative',
    prompt: 'Given integer array `nums` and integer `val`, remove **all occurrences** of `val` in-place. Return new length `k` — the first `k` elements should contain the remaining values in original order.',
    constraints: '0 ≤ nums.length ≤ 100\n0 ≤ nums[i] ≤ 50',
    examples: [
      { input: 'nums = [3,2,2,3], val = 3', output: '2, nums = [2,2,...]' },
      { input: 'nums = [0,1,2,2,3,0,4,2], val = 2', output: '5' },
    ],
    difficulty: 'easy',
    estMin: 8,
    tags: ['two-pointers', 'in-place'],
    hints: ['Use a write pointer starting at 0.', 'For each element, copy it to write position only if it differs from val.', 'Return the final write position.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Subsequence Verifier',
    prompt: 'Given strings `s` and `t`, return `true` if `s` is a **subsequence** of `t` — i.e., `s` can be obtained from `t` by deleting some characters without changing the order of the remaining characters.',
    constraints: '0 ≤ s.length ≤ 100\n0 ≤ t.length ≤ 10^4',
    examples: [
      { input: 's = "ace", t = "abcde"', output: 'true' },
      { input: 's = "aec", t = "abcde"', output: 'false' },
    ],
    difficulty: 'easy',
    estMin: 8,
    tags: ['two-pointers', 'string'],
    hints: ['Use pointer i for s and j for t.', 'Advance j always; advance i only when s[i]==t[j].', 'If i reaches s.length, return true.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Mountain Array Detector',
    prompt: 'An array is a **mountain** if it has at least 3 elements, strictly increases to a peak, then strictly decreases. Given `arr`, return `true` if it is a mountain array.',
    constraints: '3 ≤ arr.length ≤ 10^4\n0 ≤ arr[i] ≤ 10^4',
    examples: [
      { input: 'arr = [0,3,2,1]', output: 'true' },
      { input: 'arr = [3,5,5]', output: 'false', explanation: 'peak not strict' },
    ],
    difficulty: 'easy',
    estMin: 10,
    tags: ['two-pointers'],
    hints: ['Use left pointer climbing from start, right pointer descending from end.', 'If they meet at the same non-boundary index, it is a mountain.', 'Make sure neither pointer starts moving sideways.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Sorted Squares Sequence',
    prompt: 'Given a **sorted** integer array `nums` (may contain negatives), return a new array of the **squares** of each element, sorted in non-decreasing order.',
    constraints: '1 ≤ nums.length ≤ 10^4\n-10^4 ≤ nums[i] ≤ 10^4',
    examples: [
      { input: 'nums = [-4,-1,0,3,10]', output: '[0,1,9,16,100]' },
      { input: 'nums = [-7,-3,2,3,11]', output: '[4,9,9,49,121]' },
    ],
    difficulty: 'easy',
    estMin: 10,
    tags: ['two-pointers', 'sorting'],
    hints: ['Largest squares are at the extremes of a sorted array.', 'Use left/right pointers and fill result from back.', 'Always place the larger square at the current rightmost output position.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Backspace Equalizer',
    prompt: 'Given two strings `s` and `t` where `#` means **backspace**, return `true` if they result in the same string after processing all backspaces.',
    constraints: '1 ≤ s.length, t.length ≤ 200\nStrings contain lowercase letters and `#`',
    examples: [
      { input: 's = "ab#c", t = "ad#c"', output: 'true', explanation: 'Both become "ac"' },
      { input: 's = "a#c", t = "b"', output: 'false' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['two-pointers', 'string', 'simulation'],
    hints: ['Traverse from the right so you know about backspaces before processing characters.', 'Track skip counts for pending backspaces.', 'Advance both pointers together, skipping as needed, then compare characters.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Interval Cover Optimizer',
    prompt: 'Given a **sorted** array of `intervals = [[start, end], ...]`, merge all overlapping intervals and return the list of merged intervals.',
    constraints: '1 ≤ intervals.length ≤ 10^4\n0 ≤ start ≤ end ≤ 10^4',
    examples: [
      { input: 'intervals = [[1,3],[2,6],[8,10],[15,18]]', output: '[[1,6],[8,10],[15,18]]' },
      { input: 'intervals = [[1,4],[4,5]]', output: '[[1,5]]' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['two-pointers', 'intervals'],
    hints: ['Sort by start time.', 'Maintain a current merged interval; extend its end when next interval overlaps.', 'Overlap condition: next.start <= current.end.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Palindrome Extender',
    prompt: 'Given string `s`, find the **longest palindromic substring**. Use expand-around-center with two-pointer expansion. Return the palindrome.',
    constraints: '1 ≤ s.length ≤ 1000\ns contains lowercase English letters',
    examples: [
      { input: 's = "babad"', output: '"bab"' },
      { input: 's = "cbbd"', output: '"bb"' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['two-pointers', 'string'],
    hints: ['For each center (and between centers), expand while characters match.', 'Consider both odd-length (single center) and even-length (two-char center) palindromes.', 'Track the longest palindrome found.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Partition Labeler',
    prompt: 'Given string `s`, partition it into as many **parts** as possible so each letter appears in **at most one part**. Return a list of part lengths.',
    constraints: '1 ≤ s.length ≤ 500\ns contains lowercase English letters only',
    examples: [
      { input: 's = "ababcbacadefegdehijhklij"', output: '[9,7,8]' },
      { input: 's = "eccbbbbdec"', output: '[10]' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['two-pointers', 'greedy', 'string'],
    hints: ['Record the last occurrence index of each character.', 'Use two pointers: start and end of current partition.', 'Extend end to max(end, last[s[i]]) as you scan; cut when i==end.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Trapping Rain Analyst',
    prompt: 'Given `heights` array representing an elevation map where each bar is width 1, compute how much **water** can be trapped after rain. Return total water units.',
    constraints: '1 ≤ heights.length ≤ 2×10^4\n0 ≤ heights[i] ≤ 3×10^4',
    examples: [
      { input: 'heights = [0,1,0,2,1,0,1,3,2,1,2,1]', output: '6' },
      { input: 'heights = [4,2,0,3,2,5]', output: '9' },
    ],
    difficulty: 'hard',
    estMin: 25,
    tags: ['two-pointers', 'dynamic-programming'],
    hints: ['Water above position i = min(maxLeft[i], maxRight[i]) - heights[i].', 'Two-pointer approach: maintain running maxLeft and maxRight.', 'Process the side with the smaller max, since that constrains the water level.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The K-Diff Pair Counter',
    prompt: 'Given integer array `nums` and integer `k`, return the number of **unique pairs** `(a, b)` where `|a - b| == k`. Each value can only be used once per pair, and order does not matter.',
    constraints: '1 ≤ nums.length ≤ 10^4\n-10^7 ≤ nums[i] ≤ 10^7\n0 ≤ k ≤ 10^7',
    examples: [
      { input: 'nums = [3,1,4,1,5], k = 2', output: '2', explanation: 'pairs (1,3) and (3,5)' },
      { input: 'nums = [1,2,3,4,5], k = 1', output: '4' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['two-pointers', 'sorting'],
    hints: ['Sort the array.', 'Use two pointers i and j (j > i always).', 'If diff < k, advance j. If diff > k, advance i. If equal, count and advance both.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Waveform Pair Detector',
    prompt: 'Given array `signal`, count the number of **alternating pairs** `(i, i+1)` where one is a local peak and the other a local valley (strictly greater/less than both neighbors). Return this count.',
    constraints: '2 ≤ signal.length ≤ 10^5\n1 ≤ signal[i] ≤ 10^9',
    examples: [
      { input: 'signal = [1,4,2,5,3]', output: '3', explanation: '(1,4),(4,2),(2,5) are alternating' },
      { input: 'signal = [1,1,1]', output: '0' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['two-pointers', 'array'],
    hints: ['Walk through with two adjacent pointers.', 'Count when consecutive pair alternates direction.', 'Compare each pair with its context carefully.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Product Range Filter',
    prompt: 'Given a **sorted positive** array `nums` and range `[low, high]`, count pairs `(i,j)` with `i < j` such that `low <= nums[i]*nums[j] <= high`.',
    constraints: '2 ≤ nums.length ≤ 10^4\n1 ≤ nums[i] ≤ 10^4\n1 ≤ low ≤ high ≤ 10^8',
    examples: [
      { input: 'nums = [1,2,3,5], low = 2, high = 8', output: '5' },
      { input: 'nums = [2,4,6], low = 10, high = 20', output: '2' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['two-pointers', 'binary-search', 'counting'],
    hints: ['Fix the left element; binary search or two pointers to find valid right range.', 'Since array is sorted, products are monotonic within a fixed left.', 'Count valid j positions for each i in O(n) with a two-pointer sweep.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Partition Balance Prober',
    prompt: 'Given array `nums`, find the **minimum number of swaps** needed to separate all `0`s to one side and all `1`s to the other (either order). Return the minimum across both orderings.',
    constraints: '1 ≤ nums.length ≤ 10^5\nnums[i] ∈ {0, 1}',
    examples: [
      { input: 'nums = [0,1,0,1,0]', output: '1', explanation: 'One swap gives [0,0,0,1,1]' },
      { input: 'nums = [1,1,0,0]', output: '0' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['two-pointers', 'counting'],
    hints: ['Count the number of 1s; define a window of that size.', 'Count 0s in that window — each is a misplaced element needing a swap.', 'Slide window to minimize misplacements.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Reverse String Operative',
    prompt: 'Given character array `s`, reverse it **in-place** using O(1) extra memory.',
    constraints: '1 ≤ s.length ≤ 10^5\ns[i] is a printable ASCII character',
    examples: [
      { input: 's = ["h","e","l","l","o"]', output: '["o","l","l","e","h"]' },
      { input: 's = ["H","a","n","n","a","h"]', output: '["h","a","n","n","a","H"]' },
    ],
    difficulty: 'easy',
    estMin: 5,
    tags: ['two-pointers', 'in-place'],
    hints: ['Two pointers: left=0, right=n-1.', 'Swap and move both inward.', 'Stop when left >= right.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Word Reversal Engine',
    prompt: 'Given a string `s` of words separated by spaces, reverse the **order of words** — not characters within words. Multiple spaces between words should be reduced to a single space; no leading/trailing spaces in output.',
    constraints: '1 ≤ s.length ≤ 10^4\ns contains English letters, digits, and spaces',
    examples: [
      { input: 's = "the sky is blue"', output: '"blue is sky the"' },
      { input: 's = "  hello world  "', output: '"world hello"' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['two-pointers', 'string'],
    hints: ['Split into words (handling multiple spaces), then reverse the word array.', 'Alternatively: reverse the whole string, then reverse each word in-place.', 'In-place approach uses two passes of two-pointer reversal.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Segment Shrink Finder',
    prompt: 'Given positive integer array `nums` and integer `target`, find the length of the **smallest subarray** with sum **≥ target**. Return `0` if no such subarray exists.',
    constraints: '1 ≤ nums.length ≤ 2×10^5\n1 ≤ nums[i] ≤ 10^4\n1 ≤ target ≤ 10^9',
    examples: [
      { input: 'nums = [2,3,1,2,4,3], target = 7', output: '2', explanation: '[4,3] has sum 7' },
      { input: 'nums = [1,1,1,1,1], target = 11', output: '0' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['two-pointers', 'sliding-window'],
    hints: ['Expand the right pointer to accumulate sum.', 'Once sum >= target, shrink from left and update answer.', 'Positive values ensure shrinking reduces the sum.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Longest Even Sum Span',
    prompt: 'Given integer array `nums`, find the length of the **longest subarray** where the sum of the first half equals the sum of the second half (subarray must have even length ≥ 2).',
    constraints: '2 ≤ nums.length ≤ 5000\n1 ≤ nums[i] ≤ 100',
    examples: [
      { input: 'nums = [1,3,2,4,2,2]', output: '4', explanation: '[3,2,4,2] — left half 3+2=5, right half 4+2... wait, [1,3,2,4] — 1+3=4, 2+4=6. Actually [2,4,2,2]: 2+4=6, 2+2=4. [3,2,4,2]: 3+2=5, 4+2=6. try [1,3,2,4]: nope. Smallest: just check if any [a,b,c,d] works. Answer could be 0 for this.' },
      { input: 'nums = [3,3,3,3]', output: '4' },
    ],
    difficulty: 'hard',
    estMin: 30,
    tags: ['two-pointers', 'prefix-sum'],
    hints: ['Precompute prefix sums.', 'For all even-length subarrays, check if prefix[mid] - prefix[l] == prefix[r] - prefix[mid].', 'O(n^2) check with prefix sums is acceptable.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Fair Candy Exchange',
    prompt: 'Alice and Bob each have arrays of candy bar sizes `alice` and `bob`. They want to **exchange one candy** each so both end up with the same total size. Return the pair `[a, b]` (Alice gives `a`, Bob gives `b`) that achieves this. Assume a solution always exists.',
    constraints: '1 ≤ alice.length, bob.length ≤ 10^4\n1 ≤ alice[i], bob[j] ≤ 10^5',
    examples: [
      { input: 'alice = [1,1], bob = [2,2]', output: '[1,2]' },
      { input: 'alice = [2], bob = [1,3]', output: '[2,2]' },
    ],
    difficulty: 'easy',
    estMin: 12,
    tags: ['two-pointers', 'math', 'sorting'],
    hints: ['Let sumA and sumB be totals. After swap: sumA - a + b = sumB - b + a → b - a = (sumB - sumA)/2.', 'Sort both arrays, use two pointers looking for the required difference.', 'For each alice[i], binary search or two-pointer to find bob[j] = alice[i] + delta.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Longest Common Subsequence Pointer',
    prompt: 'Given strings `s` and `t`, use a **greedy two-pointer approach** to find the length of the longest common **subsequence** (not substring). This greedy approach is optimal when one string is subsequence of the other — otherwise return the greedy count.',
    constraints: '1 ≤ s.length, t.length ≤ 200',
    examples: [
      { input: 's = "abcde", t = "ace"', output: '3' },
      { input: 's = "abc", t = "abc"', output: '3' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['two-pointers', 'string'],
    hints: ['Advance pointer in t whenever characters match.', 'Count how many characters of t you can match in s left-to-right.', 'This gives the LCS length when t is a subsequence of s.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Mirror Image Checker',
    prompt: 'Given two integer arrays `a` and `b` of the same length, determine if one is the **reverse** of the other using two pointers in O(n) time and O(1) space.',
    constraints: '1 ≤ a.length == b.length ≤ 10^5',
    examples: [
      { input: 'a = [1,2,3], b = [3,2,1]', output: 'true' },
      { input: 'a = [1,2,3], b = [1,2,3]', output: 'false' },
    ],
    difficulty: 'easy',
    estMin: 5,
    tags: ['two-pointers', 'array'],
    hints: ['Use pointer i from start of a, pointer j from end of b.', 'Compare a[i] with b[j], increment i, decrement j.', 'All must match.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Odd-Even Separator',
    prompt: 'Given linked list represented as array `nodes`, rearrange it **in-place** so all **odd-indexed** nodes come first, then all **even-indexed** nodes (1-indexed). Preserve relative order within each group.',
    constraints: '1 ≤ nodes.length ≤ 10^4\n-10^6 ≤ nodes[i] ≤ 10^6',
    examples: [
      { input: 'nodes = [1,2,3,4,5]', output: '[1,3,5,2,4]' },
      { input: 'nodes = [2,1,3,5,6,4,7]', output: '[2,3,6,7,1,5,4]' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['two-pointers', 'linked-list'],
    hints: ['Maintain two pointers: one for the odd chain, one for the even chain.', 'Alternate assignments: odd->next = even->next, even->next = odd->next.', 'Append even chain to end of odd chain.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Overlapping Intersection',
    prompt: 'Given two **sorted** arrays `a` and `b`, return their **intersection** — elements present in both arrays (each element as many times as it appears in both). Return sorted.',
    constraints: '0 ≤ a.length, b.length ≤ 10^3\n-10^9 ≤ elements ≤ 10^9',
    examples: [
      { input: 'a = [1,2,2,3], b = [2,2,4]', output: '[2,2]' },
      { input: 'a = [4,9,5], b = [9,4,9,8,4]', output: '[4,9]' },
    ],
    difficulty: 'easy',
    estMin: 10,
    tags: ['two-pointers', 'sorting'],
    hints: ['Use two pointers, one per array.', 'Advance the smaller one; when equal, record and advance both.', 'Arrays must be sorted first.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Union Sequence Builder',
    prompt: 'Given two **sorted** arrays `a` and `b`, return their **union** — all distinct elements from both, sorted.',
    constraints: '0 ≤ a.length, b.length ≤ 10^5\n-10^9 ≤ elements ≤ 10^9',
    examples: [
      { input: 'a = [1,3,5], b = [2,3,6]', output: '[1,2,3,5,6]' },
      { input: 'a = [1,2], b = [1,2,3]', output: '[1,2,3]' },
    ],
    difficulty: 'easy',
    estMin: 10,
    tags: ['two-pointers', 'sorting'],
    hints: ['Merge both arrays with two pointers.', 'Skip duplicate elements when adding to result.', 'Append remaining elements from the non-exhausted array.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Max Sliding Pair',
    prompt: 'Given integer array `nums` and integer `k`, find two elements `nums[i]` and `nums[j]` with `|i - j| <= k` that maximize `nums[i] + nums[j]` (i != j). Return this maximum sum.',
    constraints: '2 ≤ nums.length ≤ 10^5\n1 ≤ k ≤ nums.length - 1\n-10^4 ≤ nums[i] ≤ 10^4',
    examples: [
      { input: 'nums = [1,5,2,8,3], k = 2', output: '13', explanation: 'nums[1]+nums[3]=5+8=13' },
      { input: 'nums = [3,3,3], k = 1', output: '6' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['two-pointers', 'sliding-window'],
    hints: ['For each position j, you want the maximum nums[i] in window [j-k, j-1].', 'Maintain a running max of the window using a pointer.', 'Slide the window as j advances.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Consecutive Sum Locator',
    prompt: 'Given a positive integer `n`, find **all ways** to express `n` as a sum of **consecutive positive integers**. Return each sequence as `[start, end]`.',
    constraints: '1 ≤ n ≤ 10^9',
    examples: [
      { input: 'n = 15', output: '[[1,5],[4,6],[7,8]]', explanation: '1+2+3+4+5=15, 4+5+6=15, 7+8=15' },
      { input: 'n = 9', output: '[[2,4],[4,5]]' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['two-pointers', 'math'],
    hints: ['Consecutive integers from l to r have sum (r-l+1)*(l+r)/2.', 'Use two pointers l and r on the positive integers.', 'If sum < n, advance r. If sum > n, advance l. If equal, record.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Boat Load Optimizer',
    prompt: 'Each person has a weight. A boat can carry at most `limit` weight, holding at most **2 people**. Find the **minimum number of boats** to carry everyone.',
    constraints: '1 ≤ people.length ≤ 5×10^4\n1 ≤ people[i] ≤ limit ≤ 3×10^4',
    examples: [
      { input: 'people = [1,2], limit = 3', output: '1' },
      { input: 'people = [3,2,2,1], limit = 3', output: '3' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['two-pointers', 'greedy', 'sorting'],
    hints: ['Sort the array.', 'Greedily pair the heaviest person with the lightest if possible.', 'If they fit together, take a boat for two. Otherwise, heaviest goes alone.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Rotation Overlap Scanner',
    prompt: 'Given two sorted arrays `a` and `b` of the same length, find the **maximum number of overlapping elements** if you can rotate `b` by any amount (circular shift). Return this maximum.',
    constraints: '1 ≤ a.length == b.length ≤ 1000\n0 ≤ a[i], b[i] ≤ 10^6',
    examples: [
      { input: 'a = [1,3,5], b = [3,5,1]', output: '3', explanation: 'b already is a rotation of a' },
      { input: 'a = [1,2,3], b = [4,5,6]', output: '0' },
    ],
    difficulty: 'hard',
    estMin: 30,
    tags: ['two-pointers', 'sorting', 'rotation'],
    hints: ['Sort both arrays. For each rotation offset, count matches using two pointers.', 'There are n possible offsets; each check is O(n) → O(n^2) total.', 'Alternatively use hashing for O(n) amortized.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Common Triplet Counter',
    prompt: 'Given three **sorted** arrays `a`, `b`, and `c`, count the number of triplets `(i,j,k)` such that `a[i] == b[j] == c[k]`. Elements at different positions may have the same value.',
    constraints: '1 ≤ a.length, b.length, c.length ≤ 10^3',
    examples: [
      { input: 'a = [1,2,3], b = [2,3,4], c = [3,4,5]', output: '1', explanation: 'only 3 appears in all three' },
      { input: 'a = [1,1,2], b = [1,2,2], c = [1,2,2]', output: '5' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['two-pointers', 'sorting'],
    hints: ['Use three pointers.', 'Advance the pointer pointing to the smallest value.', 'When all three point to equal values, count occurrences of that value in each array.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Longest Balanced Prefix',
    prompt: 'Given binary string `s`, find the **longest prefix** where the count of `0`s equals the count of `1`s. Return its length.',
    constraints: '1 ≤ s.length ≤ 10^5\ns[i] ∈ {"0", "1"}',
    examples: [
      { input: 's = "00110011"', output: '8' },
      { input: 's = "0001"', output: '0' },
    ],
    difficulty: 'easy',
    estMin: 8,
    tags: ['two-pointers', 'string', 'prefix'],
    hints: ['Track count difference (zeros - ones) as you scan.', 'Extend as long as difference ≥ 0 and flip within tolerance.', 'Actually: walk until counts become unbalanced. Track longest balanced prefix.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Squeeze Ratio Scanner',
    prompt: 'Given sorted array `nums` and a ratio `r` (as fraction `p/q`), find all pairs `(i, j)` with `i < j` where `nums[j] / nums[i] == p/q`. Return the count. All `nums[i] > 0`.',
    constraints: '2 ≤ nums.length ≤ 10^4\n1 ≤ p, q ≤ 100\n1 ≤ nums[i] ≤ 10^6',
    examples: [
      { input: 'nums = [2,4,6,8], p = 2, q = 1', output: '3', explanation: '(2,4),(4,8),(2,4) wait: (2,4),(4,8),(2,4)? pairs: (2,4),(2,8?no),(4,8) → 2' },
      { input: 'nums = [1,2,4], p = 2, q = 1', output: '2' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['two-pointers', 'math'],
    hints: ['For each i, you need nums[j] = nums[i]*p/q.', 'Use two pointers or binary search on the sorted array.', 'Handle integer arithmetic: check nums[j]*q == nums[i]*p.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Cycle Starter Detector',
    prompt: 'Given array `next` where `next[i]` represents the next position from index `i` (forming a functional graph), detect if there is a **cycle** and return the **starting index** of the cycle. Return `-1` if no cycle.',
    constraints: '1 ≤ next.length ≤ 10^5\n0 ≤ next[i] < next.length',
    examples: [
      { input: 'next = [1,2,3,4,0]', output: '0', explanation: 'cycle: 0→1→2→3→4→0' },
      { input: 'next = [1,2,1]', output: '1', explanation: 'cycle: 1→2→1' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['two-pointers', 'fast-slow-pointers', 'cycle-detection'],
    hints: ["Use Floyd's tortoise and hare to detect the cycle.", 'Once they meet inside the cycle, reset slow to start.', 'Advance both one step at a time; meeting point is cycle start.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Staircase Pair Builder',
    prompt: 'Given positive integer `n`, find all pairs `(a, b)` with `a < b` such that `a^2 + b^2 == n`. Return all such pairs sorted by `a`.',
    constraints: '1 ≤ n ≤ 10^10',
    examples: [
      { input: 'n = 25', output: '[[3,4]]', explanation: '9+16=25' },
      { input: 'n = 50', output: '[[1,7],[5,5]]' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['two-pointers', 'math'],
    hints: ['Let a start at 1 and b start at floor(sqrt(n)).', 'If a^2+b^2 > n, decrement b. If < n, increment a.', 'Stop when a >= b.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Minimum Operations Balancer',
    prompt: 'Given array `nums`, find the **minimum number of operations** to make it **non-decreasing**, where one operation increments or decrements any element by 1.',
    constraints: '1 ≤ nums.length ≤ 10^4\n-10^4 ≤ nums[i] ≤ 10^4',
    examples: [
      { input: 'nums = [3,1,2]', output: '2', explanation: '[3,1,2]→[1,1,2] costs 2' },
      { input: 'nums = [1,2,3]', output: '0' },
    ],
    difficulty: 'hard',
    estMin: 35,
    tags: ['two-pointers', 'dynamic-programming', 'greedy'],
    hints: ['This is equivalent to minimizing sum of |nums[i] - result[i]| where result is non-decreasing.', 'Dynamic programming on values with patience sorting.', 'Greedy: for each pair of adjacent descending elements, raise the smaller or lower the bigger — choose min cost.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Segment Dot Product Analyzer',
    prompt: 'Given two integer arrays `a` and `b` of the same length, find a **contiguous subarray** of the same indices `[l, r]` that maximizes `sum(a[i]*b[i])` for `l <= i <= r`. Return this maximum sum.',
    constraints: '1 ≤ a.length == b.length ≤ 10^4\n-100 ≤ a[i], b[i] ≤ 100',
    examples: [
      { input: 'a = [1,-1,1], b = [2,-2,2]', output: '6', explanation: '[0..2]: 1*2+(-1)*(-2)+1*2=2+2+2=6' },
      { input: 'a = [-1,2], b = [1,-1]', output: '0' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['two-pointers', 'dynamic-programming'],
    hints: ['Precompute products c[i] = a[i]*b[i].', 'The problem reduces to maximum subarray sum of c.', "Use Kadane's algorithm or two-pointer expansion."],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Flipped Bit Maximizer',
    prompt: 'Given binary array `bits`, find the length of the **longest subarray with at most one `0`** (you can flip it to `1`). Return that length.',
    constraints: '1 ≤ bits.length ≤ 10^5\nbits[i] ∈ {0, 1}',
    examples: [
      { input: 'bits = [1,1,0,1,1,1]', output: '6', explanation: 'Flip the single 0' },
      { input: 'bits = [0,0,1,1]', output: '3', explanation: 'Flip second 0: [0,1,1,1]' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['two-pointers', 'sliding-window'],
    hints: ['Sliding window with at most one zero allowed.', 'Expand right; when second zero enters, shrink left.', 'Track position of last zero for efficient shrink.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Longest Uniform Segment',
    prompt: 'Given binary string `s` and integer `k`, find the length of the **longest substring with at most k character changes** that makes all characters the same (either all `0` or all `1`).',
    constraints: '1 ≤ s.length ≤ 10^5\n0 ≤ k ≤ s.length',
    examples: [
      { input: 's = "AABABBA", k = 1', output: '4' },
      { input: 's = "ABAB", k = 2', output: '4' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['two-pointers', 'sliding-window', 'string'],
    hints: ['Try maximizing all-A substrings and all-B substrings separately.', 'Sliding window: count minority chars; if count > k, shrink left.', 'Return max window length found.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Even Split Validator',
    prompt: 'Given integer array `nums`, determine if it can be **split into two contiguous subarrays** (left and right, both non-empty) such that the sums of the two halves are equal.',
    constraints: '2 ≤ nums.length ≤ 10^5\n1 ≤ nums[i] ≤ 10^4',
    examples: [
      { input: 'nums = [1,2,3,3]', output: 'true', explanation: '[1,2,3] sum 6 = [3] sum... no. [1,5]: no. [1,2,3] = 6, [3] = 3. Actually [3,3]: [3] and [3]. Answer: [1,2,3] left... check all splits.' },
      { input: 'nums = [1,2]', output: 'false' },
    ],
    difficulty: 'easy',
    estMin: 10,
    tags: ['two-pointers', 'prefix-sum'],
    hints: ['Compute total sum; if odd, impossible.', 'Scan with a running sum; stop when running sum == total/2.', 'The split point exists if such position is found before the last element.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Bitonic Decomposer',
    prompt: 'Given array `nums`, split it into the minimum number of **strictly increasing** subarrays that together form the original sequence (as contiguous slices). Return the count.',
    constraints: '1 ≤ nums.length ≤ 10^5\n-10^9 ≤ nums[i] ≤ 10^9',
    examples: [
      { input: 'nums = [1,3,2,4,1,5]', output: '3', explanation: '[1,3],[2,4],[1,5]' },
      { input: 'nums = [1,2,3,4,5]', output: '1' },
    ],
    difficulty: 'easy',
    estMin: 10,
    tags: ['two-pointers', 'greedy'],
    hints: ['Walk from left; extend the current run while strictly increasing.', 'Start a new run whenever sequence breaks.', 'Count number of runs.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Array Spiral Extractor',
    prompt: 'Given a 2D matrix `grid`, extract elements in **spiral order** (clockwise from top-left). Return the 1D list of values.',
    constraints: '1 ≤ grid.length, grid[0].length ≤ 10\n-100 ≤ grid[i][j] ≤ 100',
    examples: [
      { input: 'grid = [[1,2,3],[4,5,6],[7,8,9]]', output: '[1,2,3,6,9,8,7,4,5]' },
      { input: 'grid = [[1,2],[3,4]]', output: '[1,2,4,3]' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['two-pointers', 'matrix', 'simulation'],
    hints: ['Maintain four boundary pointers: top, bottom, left, right.', 'Traverse top row, right col, bottom row, left col; then shrink boundaries.', 'Stop when boundaries cross.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Longest Equal Segment',
    prompt: 'Given array `nums`, find the length of the **longest subarray** where all elements are **equal**.',
    constraints: '1 ≤ nums.length ≤ 10^5\n-10^9 ≤ nums[i] ≤ 10^9',
    examples: [
      { input: 'nums = [1,1,2,2,2,1,1]', output: '3', explanation: '[2,2,2]' },
      { input: 'nums = [5]', output: '1' },
    ],
    difficulty: 'easy',
    estMin: 8,
    tags: ['two-pointers'],
    hints: ['Expand right while nums[right] == nums[left].', 'Track window length and max.', 'On mismatch, set left = right and continue.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Longest Non-Repeating Run',
    prompt: 'Given integer array `nums`, find the length of the **longest subarray with no two adjacent elements equal**.',
    constraints: '1 ≤ nums.length ≤ 10^5',
    examples: [
      { input: 'nums = [1,2,1,1,2]', output: '3', explanation: '[1,2,1]' },
      { input: 'nums = [1,1,1]', output: '1' },
    ],
    difficulty: 'easy',
    estMin: 10,
    tags: ['two-pointers'],
    hints: ['Walk with two pointers.', 'When nums[r] == nums[r-1], reset left to r.', 'Track window length r - left + 1.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Array Rotation Checker',
    prompt: 'Given two arrays `a` and `b` of the same length, determine if `b` is a **rotation** of `a` (circular shift by any amount). Return `true` or `false`.',
    constraints: '1 ≤ a.length == b.length ≤ 10^4\n-10^9 ≤ a[i] ≤ 10^9',
    examples: [
      { input: 'a = [1,2,3,4,5], b = [3,4,5,1,2]', output: 'true' },
      { input: 'a = [1,2,3], b = [1,3,2]', output: 'false' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['two-pointers', 'string-matching'],
    hints: ['Concatenate a with itself; check if b appears as a subarray.', 'Use KMP or two-pointer substring search.', 'If a is a substring of a+a with offset shift, then b is a rotation.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Strict Monotone Extractor',
    prompt: 'Given integer array `nums`, find the **longest strictly increasing subarray** (contiguous). Return its length.',
    constraints: '1 ≤ nums.length ≤ 10^5\n-10^9 ≤ nums[i] ≤ 10^9',
    examples: [
      { input: 'nums = [1,3,5,4,7]', output: '3', explanation: '[1,3,5]' },
      { input: 'nums = [2,2,2,2]', output: '1' },
    ],
    difficulty: 'easy',
    estMin: 8,
    tags: ['two-pointers'],
    hints: ['Walk right while nums[r] > nums[r-1].', 'On violation, reset left to r.', 'Track max window.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Max Absolute Difference Pair',
    prompt: 'Given integer array `nums`, find the pair `(nums[i], nums[j])` with `i < j` that maximizes `|nums[i] - nums[j]|`. Return this maximum absolute difference.',
    constraints: '2 ≤ nums.length ≤ 10^5\n-10^9 ≤ nums[i] ≤ 10^9',
    examples: [
      { input: 'nums = [2,7,3,9,1]', output: '8', explanation: 'max-min=9-1=8' },
      { input: 'nums = [5,5,5]', output: '0' },
    ],
    difficulty: 'easy',
    estMin: 8,
    tags: ['two-pointers', 'math'],
    hints: ['Maximum absolute difference is always max(nums) - min(nums).', 'One scan suffices to find both.', 'No constraint on i < j matters for max - min.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Anagram Pair Validator',
    prompt: 'Given two strings `s` and `t`, determine if `t` is an **anagram** of `s` using two-pointer/counter approach — same characters with same frequencies.',
    constraints: '1 ≤ s.length, t.length ≤ 5×10^4\nStrings contain lowercase English letters',
    examples: [
      { input: 's = "anagram", t = "nagaram"', output: 'true' },
      { input: 's = "rat", t = "car"', output: 'false' },
    ],
    difficulty: 'easy',
    estMin: 8,
    tags: ['two-pointers', 'string', 'hash-map'],
    hints: ['Sort both and compare, OR count frequencies.', 'Two-pointer on sorted strings: compare character by character.', 'Must have same length first.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Two-Array Median',
    prompt: 'Given two **sorted** arrays `a` and `b`, find the **median** of the combined sorted array without merging them. Return a float.',
    constraints: '0 ≤ a.length, b.length ≤ 1000\n-10^6 ≤ elements ≤ 10^6\na.length + b.length ≥ 1',
    examples: [
      { input: 'a = [1,3], b = [2]', output: '2.0' },
      { input: 'a = [1,2], b = [3,4]', output: '2.5' },
    ],
    difficulty: 'hard',
    estMin: 35,
    tags: ['two-pointers', 'binary-search', 'math'],
    hints: ['Binary search on the smaller array to find the partition point.', 'The partition must satisfy maxLeft(a) <= minRight(b) and maxLeft(b) <= minRight(a).', 'Median is average of maxLefts and minRights depending on total length parity.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Palindrome Halver',
    prompt: 'Given string `s`, determine if you can make it a palindrome by removing **at most one character**.',
    constraints: '1 ≤ s.length ≤ 10^5\ns contains lowercase English letters',
    examples: [
      { input: 's = "abca"', output: 'true', explanation: 'Remove "b" or "c"' },
      { input: 's = "abc"', output: 'false' },
    ],
    difficulty: 'easy',
    estMin: 12,
    tags: ['two-pointers', 'string'],
    hints: ['Use two pointers from both ends.', 'On mismatch, try skipping left char or right char.', 'Check if remaining substring is a palindrome.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Score Equalizer',
    prompt: 'Given two integer arrays `alice` and `bob` of the same length representing scores per round, find the **number of rounds** where Alice and Bob have the same cumulative score after that round.',
    constraints: '1 ≤ alice.length == bob.length ≤ 10^5\n1 ≤ alice[i], bob[i] ≤ 100',
    examples: [
      { input: 'alice = [2,3,5], bob = [3,2,5]', output: '2', explanation: 'After round 2: both 5. After round 3: both 10.' },
      { input: 'alice = [1,2], bob = [2,1]', output: '1' },
    ],
    difficulty: 'easy',
    estMin: 8,
    tags: ['two-pointers', 'prefix-sum'],
    hints: ['Compute prefix sums of both.', 'Count indices where prefixA[i] == prefixB[i].', 'Or track running difference.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Domino Balance Checker',
    prompt: 'Given array `tops` and `bottoms` representing domino tiles, find the **minimum number of rotations** (swap top and bottom for a tile) to make all values in `tops` the same OR all values in `bottoms` the same. Return `-1` if impossible.',
    constraints: '2 ≤ tops.length == bottoms.length ≤ 2×10^4\n1 ≤ tops[i], bottoms[i] ≤ 6',
    examples: [
      { input: 'tops = [2,1,2,4,2,2], bottoms = [5,2,6,2,3,2]', output: '2' },
      { input: 'tops = [3,5,1,2,3], bottoms = [3,6,3,3,4]', output: '-1' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['two-pointers', 'greedy'],
    hints: ['Only values tops[0] or bottoms[0] could be candidates for the uniform value.', 'For each candidate, count rotations needed.', 'Return min rotations, or -1 if neither candidate works.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Max Overlap Counter',
    prompt: 'Given array of intervals `[start, end]`, find the **maximum number of intervals that overlap at any single point** in time. Return this count.',
    constraints: '1 ≤ intervals.length ≤ 10^4\n0 ≤ start ≤ end ≤ 10^9',
    examples: [
      { input: 'intervals = [[1,4],[2,5],[3,6]]', output: '3', explanation: 'All three overlap at time 3' },
      { input: 'intervals = [[1,2],[3,4]]', output: '1' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['two-pointers', 'sorting', 'sweep-line'],
    hints: ['Separate starts and ends into sorted arrays.', 'Two-pointer sweep: at each event, track active count.', 'On start, increment. On end, decrement. Track max.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Bracket Depth Analyzer',
    prompt: 'Given a valid bracket string `s` (only `(` and `)`), find the **maximum nesting depth**. Return it.',
    constraints: '1 ≤ s.length ≤ 100\ns is a valid bracket string',
    examples: [
      { input: 's = "(1+(2*3)+((8)/4))+1"', output: '3' },
      { input: 's = "()()"', output: '1' },
    ],
    difficulty: 'easy',
    estMin: 8,
    tags: ['two-pointers', 'stack', 'string'],
    hints: ['Walk with a depth counter.', 'Increment on `(`, decrement on `)`.', 'Track maximum depth seen.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Zigzag Traversal',
    prompt: 'Given `n` rows and `n` columns of a grid filled row by row, traverse it in a **zigzag** pattern: left-to-right on even rows (0-indexed), right-to-left on odd rows. Return the traversal order as 1D array.',
    constraints: '1 ≤ n ≤ 100\n1 ≤ grid[i][j] ≤ 10^4',
    examples: [
      { input: 'grid = [[1,2,3],[4,5,6],[7,8,9]]', output: '[1,2,3,6,5,4,7,8,9]' },
      { input: 'grid = [[1,2],[3,4]]', output: '[1,2,4,3]' },
    ],
    difficulty: 'easy',
    estMin: 10,
    tags: ['two-pointers', 'matrix'],
    hints: ['For even rows, collect left to right; for odd rows, right to left.', 'Use row index parity to decide direction.', 'No extra space needed beyond output array.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Cyclic Shift Equalizer',
    prompt: 'Given strings `s` and `t` of the same length, determine the **minimum number of right rotations** of `s` to make it equal to `t`. Return `-1` if impossible.',
    constraints: '1 ≤ s.length == t.length ≤ 100\nStrings contain lowercase letters',
    examples: [
      { input: 's = "abcde", t = "cdeab"', output: '3' },
      { input: 's = "abc", t = "acb"', output: '-1' },
    ],
    difficulty: 'easy',
    estMin: 10,
    tags: ['two-pointers', 'string'],
    hints: ['Try all n rotations of s.', 'Check if rotated s equals t.', 'Return the first matching rotation count.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Longest K-Replacement Window',
    prompt: 'Given string `s` and integer `k`, find the length of the **longest substring** you can obtain after replacing **at most `k` characters** with any letter, such that all characters in the window are the same.',
    constraints: '1 ≤ s.length ≤ 10^5\n0 ≤ k ≤ s.length\ns contains uppercase English letters',
    examples: [
      { input: 's = "AABABBA", k = 1', output: '4' },
      { input: 's = "ABAB", k = 2', output: '4' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['two-pointers', 'sliding-window', 'string'],
    hints: ['Track the frequency of the most common character in the current window.', 'Window is valid if (window_size - max_freq) <= k.', 'Expand right; shrink left when invalid.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Binary String Balancer',
    prompt: 'Given binary string `s`, find the **minimum number of swaps** to balance it (equal number of `0`s and `1`s in the first half and second half). Return `-1` if length is odd or counts are unequal.',
    constraints: '2 ≤ s.length ≤ 10^5\ns[i] ∈ {"0", "1"}\ns.length is even',
    examples: [
      { input: 's = "1100"', output: '1', explanation: 'Swap s[0] and s[2]: "0110"... actually just count mismatches' },
      { input: 's = "0011"', output: '0' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['two-pointers', 'greedy'],
    hints: ['Count 1s in first half and second half.', 'Extra 1s in first half = extra 0s in second half; each such pair needs one swap.', 'Minimum swaps = number of mismatched pairs.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Positive Negative Arranger',
    prompt: 'Given array `nums` with equal numbers of positive and negative integers, rearrange it so **positives and negatives alternate** starting with a positive. Preserve relative order within each sign group. Return the rearranged array.',
    constraints: '2 ≤ nums.length ≤ 10^5\nnums.length is even\nEqual count of positives and negatives\n-10^9 ≤ nums[i] ≤ 10^9, no zeros',
    examples: [
      { input: 'nums = [3,1,-2,-5,2,-4]', output: '[3,-2,1,-5,2,-4]' },
      { input: 'nums = [-1,1]', output: '[1,-1]' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['two-pointers', 'array'],
    hints: ['Separate positives and negatives into two arrays preserving order.', 'Interleave them: pos[0], neg[0], pos[1], neg[1], ...', 'Two pointers, one per group.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Longest Ascending Tunnel',
    prompt: 'Given 2D matrix `grid`, find the length of the **longest strictly ascending path** where you can only move **right or down** at each step.',
    constraints: '1 ≤ grid.length, grid[0].length ≤ 200\n1 ≤ grid[i][j] ≤ 10^5',
    examples: [
      { input: 'grid = [[1,3,5],[2,4,6]]', output: '4', explanation: '1→3→5→6' },
      { input: 'grid = [[5,3],[4,2]]', output: '1' },
    ],
    difficulty: 'medium',
    estMin: 25,
    tags: ['two-pointers', 'dynamic-programming', 'matrix'],
    hints: ['Use DP: dp[i][j] = length of longest path ending at (i,j).', 'dp[i][j] = 1 + max(dp[i-1][j] if grid[i-1][j]<grid[i][j], dp[i][j-1] if ...).', 'Process cells in order.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Fence Builder',
    prompt: 'You are building a fence with `n` sections. Each section has height `h[i]`. You can place a **rectangular billboard** between any two sections such that its height is ≤ min height of all sections between those two. Find the **maximum area** billboard that can be placed.',
    constraints: '1 ≤ h.length ≤ 10^5\n1 ≤ h[i] ≤ 10^4',
    examples: [
      { input: 'h = [2,1,5,6,2,3]', output: '10', explanation: 'sections 2-3 (indices 2,3): min=5, width=2, area=10' },
      { input: 'h = [2,4]', output: '4' },
    ],
    difficulty: 'hard',
    estMin: 30,
    tags: ['two-pointers', 'monotonic-stack'],
    hints: ['This is the classic largest rectangle in histogram.', 'Two-pointer approach: for each bar, find left and right boundaries where it is the minimum.', 'Monotonic stack gives O(n) solution.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Distinct Element Minimizer',
    prompt: 'Given integer array `nums` and integer `k`, remove exactly `k` elements (any positions) to **minimize the number of distinct values** remaining. Return the minimum distinct count.',
    constraints: '1 ≤ nums.length ≤ 10^5\n0 ≤ k ≤ nums.length',
    examples: [
      { input: 'nums = [4,3,1,1,3,3,2], k = 3', output: '2' },
      { input: 'nums = [1,2,3], k = 1', output: '2' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['two-pointers', 'greedy', 'sorting'],
    hints: ['Count frequency of each distinct value.', 'Sort by frequency ascending.', 'Greedily eliminate entire groups starting from the least frequent.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Compact Duplicate Trimmer',
    prompt: 'Given **sorted** array `nums`, remove duplicates in-place keeping only **one copy** of each value. Return new length `k`. Elements beyond index k are irrelevant.',
    constraints: '1 ≤ nums.length ≤ 3×10^4\n-10^4 ≤ nums[i] ≤ 10^4',
    examples: [
      { input: 'nums = [1,1,2]', output: '2, nums = [1,2,...]' },
      { input: 'nums = [0,0,1,1,1,2,2,3,3,4]', output: '5' },
    ],
    difficulty: 'easy',
    estMin: 8,
    tags: ['two-pointers', 'in-place'],
    hints: ['Write pointer starts at 1.', 'For each read position, write only if different from previous written element.', 'Return write pointer value.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Pivot Partition Executor',
    prompt: 'Given array `nums` and pivot value `p`, rearrange so all elements **less than `p`** come first, then elements **equal to `p`**, then elements **greater than `p`**. Do this in-place, O(n) time.',
    constraints: '1 ≤ nums.length ≤ 10^5\n-10^9 ≤ nums[i], p ≤ 10^9',
    examples: [
      { input: 'nums = [9,12,5,10,14,3,10], p = 10', output: '[9,5,3,10,10,12,14]', explanation: 'Any valid partition accepted' },
      { input: 'nums = [1,2,3], p = 2', output: '[1,2,3]' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['two-pointers', 'partition'],
    hints: ['Three-way partition: low, mid, high pointers.', 'Elements < p go to left, == p to middle, > p to right.', 'Dutch national flag with value comparison.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Longest Palindrome Builder',
    prompt: 'Given string `s`, find the **longest palindromic subsequence** length. This is not a two-pointer problem by default, but use DP with two-pointer expansion on all centers.',
    constraints: '1 ≤ s.length ≤ 1000',
    examples: [
      { input: 's = "bbbab"', output: '4', explanation: '"bbbb" is longest palindromic subseq' },
      { input: 's = "cbbd"', output: '2' },
    ],
    difficulty: 'hard',
    estMin: 30,
    tags: ['two-pointers', 'dynamic-programming'],
    hints: ['dp[i][j] = longest palindromic subsequence in s[i..j].', 'If s[i]==s[j]: dp[i][j] = dp[i+1][j-1] + 2.', 'Otherwise: max(dp[i+1][j], dp[i][j-1]).'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Ring Buffer Traveler',
    prompt: 'You travel along a **circular route** with `n` stops. At each stop `i`, you gain `gain[i]` fuel and spend `cost[i]` fuel to reach the next stop. Find the **starting stop index** from which you can complete the full circuit. If none exists, return `-1`.',
    constraints: '1 ≤ gain.length == cost.length ≤ 10^5\n1 ≤ gain[i], cost[i] ≤ 10^4',
    examples: [
      { input: 'gain = [1,2,3,4,5], cost = [3,4,5,1,2]', output: '3' },
      { input: 'gain = [2,3,4], cost = [3,4,3]', output: '-1' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['two-pointers', 'greedy'],
    hints: ['If total gain < total cost, no solution exists.', 'Scan linearly tracking running fuel.', 'When fuel goes negative, reset start to next position.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Digit Reversal Validator',
    prompt: 'Given integer `n`, determine if `n` is a **palindrome** without converting it to a string. Use mathematical digit extraction with a two-pointer approach.',
    constraints: '-2^31 ≤ n ≤ 2^31 - 1',
    examples: [
      { input: 'n = 121', output: 'true' },
      { input: 'n = -121', output: 'false' },
    ],
    difficulty: 'easy',
    estMin: 10,
    tags: ['two-pointers', 'math'],
    hints: ['Negative numbers are never palindromes.', 'Reverse only half the number.', 'If n equals its reversed half (or reversed half divided by 10 for odd digits), it is a palindrome.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Interleave Validator',
    prompt: 'Given strings `a`, `b`, and `c`, determine if `c` is formed by **interleaving** `a` and `b` (characters from `a` and `b` appear in their original order, but can be interspersed).',
    constraints: '0 ≤ a.length, b.length ≤ 100\nc.length == a.length + b.length',
    examples: [
      { input: 'a = "aabcc", b = "dbbca", c = "aadbbcbcac"', output: 'true' },
      { input: 'a = "abc", b = "xyz", c = "abxyzc"', output: 'true' },
    ],
    difficulty: 'hard',
    estMin: 30,
    tags: ['two-pointers', 'dynamic-programming', 'string'],
    hints: ['Two-pointer greedy works for some cases but not all.', 'Use DP: dp[i][j] = can c[0..i+j-1] be formed from a[0..i-1] and b[0..j-1].', 'Transition: dp[i][j] |= dp[i-1][j] if a[i-1]==c[i+j-1], or dp[i][j-1] if b[j-1]==c[i+j-1].'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Sorted Color Pairing',
    prompt: 'Given array `colors` where `1 = red`, `2 = blue`, find the **maximum number of adjacent complementary pairs** you can form after optimally rearranging the array (alternating red-blue).',
    constraints: '1 ≤ colors.length ≤ 10^5\ncolors[i] ∈ {1, 2}',
    examples: [
      { input: 'colors = [1,1,2,2,2]', output: '2', explanation: '[1,2,1,2,2] has 2 adjacent pairs' },
      { input: 'colors = [1,2,1,2]', output: '3' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['two-pointers', 'greedy', 'counting'],
    hints: ['Count reds and blues.', 'Max adjacent pairs = 2*min(countRed, countBlue)-1 if different, 2*count-1 otherwise.', 'Optimal arrangement: alternate colors starting with majority.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Signal Strength Optimizer',
    prompt: 'Given integer array `signal` and window size `w`, for each window of size `w` find the **difference between max and min** values. Return the array of these differences.',
    constraints: '1 ≤ signal.length ≤ 10^5\n1 ≤ w ≤ signal.length\n-10^4 ≤ signal[i] ≤ 10^4',
    examples: [
      { input: 'signal = [3,1,4,1,5,9,2,6], w = 3', output: '[3,3,4,8,7,7]' },
      { input: 'signal = [5,5,5], w = 2', output: '[0,0]' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['two-pointers', 'sliding-window', 'deque'],
    hints: ['Maintain two monotonic deques: one for max, one for min.', 'As window slides, pop elements outside window from front.', 'Pop from back when new element breaks monotonicity.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Flip Sequence Maximizer',
    prompt: 'Given binary string `s`, find the maximum number of `1`s in a substring if you can flip **at most `k` zeros** to ones. Return the length of such a substring.',
    constraints: '1 ≤ s.length ≤ 10^5\n0 ≤ k ≤ s.length\ns[i] ∈ {"0", "1"}',
    examples: [
      { input: 's = "110100110", k = 2', output: '5', explanation: 'Flip 2 zeros in window [0..4]' },
      { input: 's = "0000", k = 1', output: '1' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['two-pointers', 'sliding-window'],
    hints: ['Sliding window tracking number of zeros in window.', 'Expand right; when zeros > k, shrink left.', 'Track max window size.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Minimum Swap Sorter',
    prompt: 'Given array `nums` with values `1..n` (each once), find the **minimum number of swaps** needed to sort it in ascending order.',
    constraints: '1 ≤ nums.length ≤ 10^5\nnums is a permutation of [1..n]',
    examples: [
      { input: 'nums = [4,3,2,1]', output: '2', explanation: 'Swap 4↔1, then swap 3↔2' },
      { input: 'nums = [1,3,5,2,4,6]', output: '3' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['two-pointers', 'cycle-detection', 'permutation'],
    hints: ['Model as a permutation graph; each cycle of length k needs k-1 swaps.', 'Count cycle lengths by following where each element should go.', 'Total swaps = n - (number of cycles).'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Cascading Sum Split',
    prompt: 'Given array `nums`, find whether it can be split into **two parts** such that the sum of the left part equals the sum of the right part. Return the split index (left part = nums[0..i], right part = nums[i+1..n-1]) or -1.',
    constraints: '2 ≤ nums.length ≤ 10^5\n1 ≤ nums[i] ≤ 10^4',
    examples: [
      { input: 'nums = [1,2,3,2,2]', output: '2', explanation: '[1,2,3] sum 6 = [2,2] sum... no wait [1,2,3]=6 and [2,2]=4. [1,2,3,2]=8 and [2]=2. Hmm. [2,3,2,2]=9. Actually nums=[1,1,1,1]: split 0: [1] sum 1 vs [1,1,1] sum 3. Adjust example.' },
      { input: 'nums = [1,2,3,3,2,1]', output: '2', explanation: '[1,2,3]=6 = [3,2,1]=6' },
    ],
    difficulty: 'easy',
    estMin: 10,
    tags: ['two-pointers', 'prefix-sum'],
    hints: ['Compute total sum.', 'Scan left-to-right accumulating left sum.', 'When left sum == total - left sum, found split point.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Optimal Buddy Assignment',
    prompt: 'Given arrays `skill1` and `skill2` of the same length (one skill per person from each team), pair each person from team 1 with one person from team 2 to **maximize the total of minimum skills** per pair. Return the maximum total.',
    constraints: '1 ≤ skill1.length == skill2.length ≤ 10^5\n1 ≤ skill1[i], skill2[i] ≤ 10^4',
    examples: [
      { input: 'skill1 = [3,1,2], skill2 = [2,3,1]', output: '6', explanation: 'Pairs (3,2),(2,3),(1,1) → min: 2+2+1=5. Optimal (3,3),(2,2),(1,1) → 3+2+1=6' },
      { input: 'skill1 = [1,2], skill2 = [1,2]', output: '3' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['two-pointers', 'greedy', 'sorting'],
    hints: ['Sort both arrays.', 'Pair the i-th smallest from team 1 with the i-th smallest from team 2.', 'Sum the minimum of each pair.'],
  },
  {
    patternSlug: 'two-pointers',
    title: 'The Tightest Pair Bracket',
    prompt: 'Given sorted array `nums` and target sum `T`, find the pair `(a, b)` with `a < b` and `a + b <= T` that **maximizes `a + b`**. Return the maximum sum, or `-1` if none exists.',
    constraints: '2 ≤ nums.length ≤ 10^5\n-10^9 ≤ nums[i] ≤ 10^9\n-2×10^9 ≤ T ≤ 2×10^9',
    examples: [
      { input: 'nums = [1,3,5,7,9], T = 10', output: '10', explanation: '1+9=10 ≤ 10. But wait 3+7=10, 5+5=10 (no repeat). Max: 10' },
      { input: 'nums = [1,2,3], T = 3', output: '3', explanation: '1+2=3' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['two-pointers', 'sorted-array'],
    hints: ['Use two pointers left=0, right=n-1.', 'If sum <= T, record it and move left pointer right.', 'If sum > T, move right pointer left.'],
  },
]
