type ProblemExample = { input: string; output: string; explanation?: string }
type ProblemSeed = {
  patternSlug: string
  title: string
  prompt: string
  constraints: string
  examples: ProblemExample[]
  difficulty: 'easy' | 'medium' | 'hard'
  estMin: number
  tags: string[]
  hints: string[]
}
export const PROBLEMS_BATCH_10: ProblemSeed[] = [
  {
    patternSlug: 'sliding-window',
    title: 'The Fixed Frame Analyzer',
    prompt: 'Given integer array `nums` and integer `k`, return the **maximum sum** of any contiguous subarray of length exactly `k`.',
    constraints: '1 ≤ k ≤ nums.length ≤ 10^5\n-10^4 ≤ nums[i] ≤ 10^4',
    examples: [
      { input: 'nums = [2,1,5,1,3,2], k = 3', output: '9', explanation: '[5,1,3]' },
      { input: 'nums = [2,3,4,1,5], k = 2', output: '7', explanation: '[3,4]' },
    ],
    difficulty: 'easy',
    estMin: 10,
    tags: ['sliding-window', 'fixed-window'],
    hints: ['Compute sum of first k elements as initial window.', 'Slide: add right element, subtract leftmost.', 'Track maximum sum.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Average Threshold Detector',
    prompt: 'Given array `nums` and integer `k`, find all starting indices of subarrays of length `k` whose **average is ≥ threshold**. Return the count.',
    constraints: '1 ≤ k ≤ nums.length ≤ 10^5\n0 ≤ nums[i] ≤ 10^4\n0 ≤ threshold ≤ 10^4',
    examples: [
      { input: 'nums = [2,2,2,2,5,5,5,8], k = 3, threshold = 4', output: '3' },
      { input: 'nums = [1,1,1,1,1], k = 1, threshold = 0', output: '5' },
    ],
    difficulty: 'easy',
    estMin: 10,
    tags: ['sliding-window', 'fixed-window'],
    hints: ['Fixed window of size k.', 'Sum of window ≥ k * threshold means average ≥ threshold.', 'Slide and count qualifying windows.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Distinct Color Window',
    prompt: 'Given string `s`, find the length of the **longest substring with all distinct characters**.',
    constraints: '1 ≤ s.length ≤ 5×10^4\ns contains English letters, digits, symbols',
    examples: [
      { input: 's = "abcabcbb"', output: '3', explanation: '"abc"' },
      { input: 's = "bbbbb"', output: '1' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['sliding-window', 'hash-map'],
    hints: ['Maintain a set of characters in current window.', 'Expand right; when duplicate found, shrink left until no duplicate.', 'Track max window size.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Minimal Anagram Frame',
    prompt: 'Given strings `s` and `p`, find all starting indices in `s` where an **anagram of `p`** begins. Return sorted list of indices.',
    constraints: '1 ≤ p.length ≤ s.length ≤ 3×10^4\nStrings contain lowercase letters',
    examples: [
      { input: 's = "cbaebabacd", p = "abc"', output: '[0,6]' },
      { input: 's = "abab", p = "ab"', output: '[0,1,2]' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['sliding-window', 'hash-map', 'string'],
    hints: ['Fixed window of length p.length.', 'Maintain character frequency count for current window vs p.', 'When all frequencies match, window is an anagram.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The K-Budget Signal Tracker',
    prompt: 'Given binary array `ops` (0 = idle, 1 = active), find the **maximum number of active slots** in any window of size `k`.',
    constraints: '1 ≤ k ≤ ops.length ≤ 10^5\nops[i] ∈ {0, 1}',
    examples: [
      { input: 'ops = [1,1,0,1,1,0,1], k = 4', output: '3' },
      { input: 'ops = [0,0,1,0,1,1,1], k = 3', output: '3' },
    ],
    difficulty: 'easy',
    estMin: 8,
    tags: ['sliding-window', 'fixed-window'],
    hints: ['Fixed window of size k.', 'Count 1s in window.', 'Slide and track maximum count.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Minimum Coverage Window',
    prompt: 'Given string `s` and string `t`, find the **minimum window substring** of `s` that contains all characters of `t` (including duplicates). Return `""` if none.',
    constraints: '1 ≤ s.length ≤ 10^5\n1 ≤ t.length ≤ t.length\nStrings contain uppercase and lowercase letters',
    examples: [
      { input: 's = "ADOBECODEBANC", t = "ABC"', output: '"BANC"' },
      { input: 's = "a", t = "aa"', output: '""' },
    ],
    difficulty: 'hard',
    estMin: 30,
    tags: ['sliding-window', 'hash-map', 'string'],
    hints: ['Expand right to include all chars of t; shrink left while still valid.', 'Track how many required characters are satisfied.', 'Record minimum window when all chars satisfied.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Longest Valid Bracket Span',
    prompt: 'Given string `s` of `(` and `)`, find the length of the **longest contiguous substring** of valid (balanced) parentheses.',
    constraints: '1 ≤ s.length ≤ 3×10^4\ns[i] ∈ {"(", ")"}',
    examples: [
      { input: 's = "(()"', output: '2' },
      { input: 's = ")()())"', output: '4' },
    ],
    difficulty: 'hard',
    estMin: 25,
    tags: ['sliding-window', 'stack', 'string'],
    hints: ['Use a stack storing indices. Push index of `(`, pop on `)`.', 'When stack empty on `)`, mark as new start.', 'Max valid span = current index - top of stack.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Burst Profit Tracker',
    prompt: 'Given integer array `profits` and window size `k`, find the **maximum total profit** achievable by choosing exactly one contiguous window of size `k` and skipping the rest.',
    constraints: '1 ≤ k ≤ profits.length ≤ 10^5\n-10^4 ≤ profits[i] ≤ 10^4',
    examples: [
      { input: 'profits = [-2,1,-3,4,-1,2,1,-5,4], k = 4', output: '6', explanation: '[4,-1,2,1]=6' },
      { input: 'profits = [1,2,3,4], k = 2', output: '7', explanation: '[3,4]' },
    ],
    difficulty: 'easy',
    estMin: 10,
    tags: ['sliding-window', 'fixed-window'],
    hints: ['Compute fixed-window sums.', 'Return the maximum.', 'Slide in O(n).'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Frequency Quota Window',
    prompt: 'Given string `s` and integer `k`, find the length of the **longest substring** where no character appears more than `k` times.',
    constraints: '1 ≤ s.length ≤ 10^5\n1 ≤ k ≤ 10^5\ns contains lowercase letters',
    examples: [
      { input: 's = "aabbcc", k = 1', output: '2', explanation: 'e.g. "ab"' },
      { input: 's = "aaabbb", k = 2', output: '4', explanation: '"aabb"' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['sliding-window', 'hash-map'],
    hints: ['Variable window. Track frequency map of chars in window.', 'When any char exceeds k, shrink left.', 'Track max window size.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Sub-Array Product Filter',
    prompt: 'Given positive integer array `nums` and integer `k`, count subarrays where the **product of all elements is strictly less than `k`**.',
    constraints: '1 ≤ nums.length ≤ 3×10^4\n1 ≤ nums[i] ≤ 1000\n0 ≤ k ≤ 10^6',
    examples: [
      { input: 'nums = [10,5,2,6], k = 100', output: '8' },
      { input: 'nums = [1,2,3], k = 0', output: '0' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['sliding-window', 'product'],
    hints: ['Expand right; multiply new element into product.', 'Shrink left while product >= k.', 'Each valid window ending at right contributes (right - left + 1) subarrays.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Max Window Deque',
    prompt: 'Given array `nums` and integer `k`, return the **maximum value** in each sliding window of size `k`.',
    constraints: '1 ≤ nums.length ≤ 10^5\n-10^4 ≤ nums[i] ≤ 10^4\n1 ≤ k ≤ nums.length',
    examples: [
      { input: 'nums = [1,3,-1,-3,5,3,6,7], k = 3', output: '[3,3,5,5,6,7]' },
      { input: 'nums = [1], k = 1', output: '[1]' },
    ],
    difficulty: 'hard',
    estMin: 25,
    tags: ['sliding-window', 'deque', 'monotonic'],
    hints: ['Use a monotonic decreasing deque storing indices.', 'Front of deque is always the max of the current window.', 'Remove indices outside window from front; remove smaller elements from back.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Min Window Deque',
    prompt: 'Given array `nums` and integer `k`, return the **minimum value** in each sliding window of size `k`.',
    constraints: '1 ≤ nums.length ≤ 10^5\n-10^4 ≤ nums[i] ≤ 10^4\n1 ≤ k ≤ nums.length',
    examples: [
      { input: 'nums = [3,1,2,4,5,1,2], k = 3', output: '[1,1,2,1,1]' },
      { input: 'nums = [5,3,1], k = 2', output: '[3,1]' },
    ],
    difficulty: 'hard',
    estMin: 25,
    tags: ['sliding-window', 'deque', 'monotonic'],
    hints: ['Use a monotonic increasing deque.', 'Front = minimum. Maintain indices in window.', 'Remove larger elements from back on expansion.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Longest Ones Stretch',
    prompt: 'Given binary array `nums`, find the **maximum number of consecutive `1`s** if you flip at most **one `0`**.',
    constraints: '1 ≤ nums.length ≤ 10^5\nnums[i] ∈ {0, 1}',
    examples: [
      { input: 'nums = [1,0,1,1,0]', output: '4' },
      { input: 'nums = [1,0,1,1,0,1]', output: '4' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['sliding-window'],
    hints: ['Track count of zeros in window.', 'Allow at most 1 zero; shrink left when count > 1.', 'Answer is max window size.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The K-Distinct Character Frame',
    prompt: 'Given string `s` and integer `k`, find the length of the **longest substring with at most `k` distinct characters**.',
    constraints: '1 ≤ s.length ≤ 10^5\n1 ≤ k ≤ 26',
    examples: [
      { input: 's = "eceba", k = 2', output: '3', explanation: '"ece"' },
      { input: 's = "aa", k = 1', output: '2' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['sliding-window', 'hash-map'],
    hints: ['Track frequency of chars in window.', 'When distinct count > k, shrink left until it drops to k.', 'Track max window size.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Exactly Two Distinct Merger',
    prompt: 'Given string `s`, count the number of **substrings with exactly 2 distinct characters**.',
    constraints: '1 ≤ s.length ≤ 10^4\ns contains lowercase letters',
    examples: [
      { input: 's = "abc"', output: '2', explanation: '"ab","bc"' },
      { input: 's = "aba"', output: '4', explanation: '"ab","ba","aba","aba"... actually "ab","ba","aba" = 3. Check.' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['sliding-window', 'hash-map', 'counting'],
    hints: ['Use the identity: exactly(k) = atMost(k) - atMost(k-1).', 'atMost(k) counts substrings with at most k distinct chars.', 'Compute both with sliding window.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Palindrome Window Detector',
    prompt: 'Given string `s` and integer `k`, find the **minimum number of character replacements** to make any window of length `k` a palindrome. Return the minimum for the best window.',
    constraints: '1 ≤ k ≤ s.length ≤ 10^4\ns contains lowercase letters\nk is odd',
    examples: [
      { input: 's = "abcba", k = 5', output: '0' },
      { input: 's = "abcde", k = 3', output: '1' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['sliding-window', 'string'],
    hints: ['For each window of size k, count mismatched symmetric pairs.', 'Fixed window of size k; slide it.', 'Mismatches = pairs where s[l+i] != s[r-i]; replacements = mismatches.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Subarray Sum Equals K',
    prompt: 'Given integer array `nums` and integer `k`, return the total number of **continuous subarrays** whose sum equals `k`.',
    constraints: '1 ≤ nums.length ≤ 2×10^4\n-10^3 ≤ nums[i] ≤ 10^3\n-10^7 ≤ k ≤ 10^7',
    examples: [
      { input: 'nums = [1,1,1], k = 2', output: '2' },
      { input: 'nums = [1,2,3], k = 3', output: '2' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['sliding-window', 'hash-map', 'prefix-sum'],
    hints: ['Prefix sum + hash map approach.', 'For each index i, count how many previous prefix sums equal prefixSum[i] - k.', 'Negatives prevent pure two-pointer; use hash map.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Network Packet Smoother',
    prompt: 'Given array of packet sizes `sizes` and window size `w`, compute a **smoothed array** where each element is the **floor average** of itself and the `w-1` elements before it (or all available if fewer).',
    constraints: '1 ≤ sizes.length ≤ 10^4\n1 ≤ w ≤ sizes.length\n1 ≤ sizes[i] ≤ 10^5',
    examples: [
      { input: 'sizes = [1,100,50,10,25,70], w = 3', output: '[1,50,50,53,28,35]' },
      { input: 'sizes = [4,3,2,1], w = 2', output: '[4,3,2,1]' },
    ],
    difficulty: 'easy',
    estMin: 10,
    tags: ['sliding-window', 'fixed-window'],
    hints: ['Use a running sum; subtract element leaving window.', 'Window size shrinks at start: min(w, i+1).', 'Floor divide sum by window size.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Coverage Gap Minimizer',
    prompt: 'Given sorted array `intervals` of `[start, end]` and query points array `queries`, for each query point find the **minimum length interval** that contains it. Return -1 if no such interval.',
    constraints: '1 ≤ intervals.length ≤ 10^5\n1 ≤ queries.length ≤ 10^5\n0 ≤ start ≤ end ≤ 10^7',
    examples: [
      { input: 'intervals = [[1,4],[2,4],[3,6],[4,4]], queries = [2,3,4,5]', output: '[3,3,1,4]' },
      { input: 'intervals = [[2,3],[2,5],[1,8]], queries = [2]', output: '[2]' },
    ],
    difficulty: 'hard',
    estMin: 30,
    tags: ['sliding-window', 'sorting', 'binary-search'],
    hints: ['Sort queries with their original indices.', 'Sort intervals by start; use pointer to add intervals starting before query.', 'Use min-heap on interval lengths; pop expired intervals.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Jump Game Window',
    prompt: 'Given array `jumps` where `jumps[i]` is the max jump length from index `i`, return `true` if you can reach the last index starting from index 0.',
    constraints: '1 ≤ jumps.length ≤ 10^4\n0 ≤ jumps[i] ≤ 10^5',
    examples: [
      { input: 'jumps = [2,3,1,1,4]', output: 'true' },
      { input: 'jumps = [3,2,1,0,4]', output: 'false' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['sliding-window', 'greedy'],
    hints: ['Track the furthest reachable index at each step.', 'If current index exceeds max reach, return false.', 'If max reach >= last index, return true.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Fruit Basket Collector',
    prompt: 'You are picking fruits along a row. You have two baskets, each holding **one type** of fruit. Find the maximum number of fruits you can collect in a contiguous subarray using at most 2 distinct fruit types.',
    constraints: '1 ≤ fruits.length ≤ 10^5\n0 ≤ fruits[i] ≤ fruits.length',
    examples: [
      { input: 'fruits = [1,2,1]', output: '3' },
      { input: 'fruits = [0,1,2,2]', output: '3' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['sliding-window', 'hash-map'],
    hints: ['Longest subarray with at most 2 distinct values.', 'Standard variable window with frequency map.', 'Shrink left when distinct count exceeds 2.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Sum Divisibility Window',
    prompt: 'Given integer array `nums` and integer `k`, return the number of **subarrays of length exactly `k` whose sum is divisible by `k`**.',
    constraints: '1 ≤ k ≤ nums.length ≤ 3×10^4\n-10^4 ≤ nums[i] ≤ 10^4',
    examples: [
      { input: 'nums = [4,5,0,-2,-3,1], k = 5', output: '7' },
      { input: 'nums = [5], k = 9', output: '0' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['sliding-window', 'prefix-sum', 'modular-arithmetic'],
    hints: ['Prefix sum modulo k.', 'Subarray sum divisible by k ↔ prefix[r] % k == prefix[l] % k.', 'Count pairs with equal prefix-mod using hash map.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The String Permutation Probe',
    prompt: 'Given strings `s1` and `s2`, return `true` if any **permutation of `s1`** is a substring of `s2`.',
    constraints: '1 ≤ s1.length, s2.length ≤ 10^4\nStrings contain lowercase letters',
    examples: [
      { input: 's1 = "ab", s2 = "eidbaooo"', output: 'true', explanation: '"ba" is in s2' },
      { input: 's1 = "ab", s2 = "eidboaoo"', output: 'false' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['sliding-window', 'hash-map', 'string'],
    hints: ['Fixed window of size s1.length in s2.', 'Compare frequency maps.', 'Slide window and update frequency diff.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Threshold Subarray Counter',
    prompt: 'Given integer array `nums` and integer `limit`, count subarrays where the **maximum element minus minimum element ≤ limit**.',
    constraints: '1 ≤ nums.length ≤ 10^5\n0 ≤ limit ≤ 10^9\n0 ≤ nums[i] ≤ 10^9',
    examples: [
      { input: 'nums = [2,1,4,3], limit = 2', output: '7' },
      { input: 'nums = [2,2,2], limit = 0', output: '6' },
    ],
    difficulty: 'hard',
    estMin: 30,
    tags: ['sliding-window', 'deque', 'monotonic'],
    hints: ['Use two deques: one for max, one for min.', 'Expand right; shrink left when max - min > limit.', 'Each valid window ending at right adds (right - left + 1) subarrays.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Equal Sum Partition Scanner',
    prompt: 'Given array `nums`, find the number of ways to split it into **three non-empty parts** such that all three parts have **equal sum**.',
    constraints: '3 ≤ nums.length ≤ 5×10^4\n-10^4 ≤ nums[i] ≤ 10^4',
    examples: [
      { input: 'nums = [0,2,-3,2,0,1,0]', output: '6' },
      { input: 'nums = [0,0,0,0]', output: '3' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['sliding-window', 'prefix-sum', 'counting'],
    hints: ['Total must be divisible by 3.', 'Find indices where prefix sum = total/3 and 2*total/3.', 'For each second-cut position, count valid first-cut positions before it.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Longest Subarray After Deletion',
    prompt: 'Given binary array `nums`, find the length of the **longest subarray of `1`s** after deleting **exactly one element** (any element).',
    constraints: '1 ≤ nums.length ≤ 10^5\nnums[i] ∈ {0, 1}',
    examples: [
      { input: 'nums = [1,1,0,1]', output: '3' },
      { input: 'nums = [0,1,1,1,0,1,1,0,1]', output: '5' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['sliding-window'],
    hints: ['Window can have at most one 0.', 'Expand right; if second 0 enters, shrink left past first 0.', 'Answer is max window - 1 (for the deleted element).'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Repeated DNA Sequence Hunter',
    prompt: 'Given DNA string `s`, find all **10-character-long sequences** that appear **more than once**.',
    constraints: '1 ≤ s.length ≤ 10^5\ns[i] ∈ {A, C, G, T}',
    examples: [
      { input: 's = "AAAAACCCCCAAAAACCCCCCAAAAAGGGTTT"', output: '["AAAAACCCCC","CCCCCAAAAA"]' },
      { input: 's = "AAAAAAAAAAAAA"', output: '["AAAAAAAAAA"]' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['sliding-window', 'hash-map', 'string'],
    hints: ['Fixed window of size 10.', 'Use a hash set to track seen substrings.', 'When a substring is seen again, add to result set.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Palindrome Partition Counter',
    prompt: 'Given string `s` and integer `k`, return the **minimum number of changes** to partition `s` into `k` palindromic substrings.',
    constraints: '1 ≤ k ≤ s.length ≤ 100\ns contains lowercase letters',
    examples: [
      { input: 's = "abc", k = 2', output: '1' },
      { input: 's = "aabbc", k = 3', output: '0' },
    ],
    difficulty: 'hard',
    estMin: 35,
    tags: ['sliding-window', 'dynamic-programming'],
    hints: ['cost(i,j) = number of changes to make s[i..j] a palindrome = mismatched symmetric pairs.', 'DP: dp[i][j] = min changes to partition first i chars into j palindromes.', 'Transition: dp[i][j] = min over all splits of dp[m][j-1] + cost(m+1, i).'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Stock Trade Window',
    prompt: 'Given price array `prices` and integer `k` (number of allowed transactions), find the **maximum profit** from at most `k` buy-sell transactions (buy before sell, no overlapping).',
    constraints: '1 ≤ prices.length ≤ 1000\n0 ≤ prices[i] ≤ 1000\n1 ≤ k ≤ 100',
    examples: [
      { input: 'prices = [2,4,1,7], k = 2', output: '8', explanation: 'Buy at 2, sell at 4 (+2), buy at 1, sell at 7 (+6)' },
      { input: 'prices = [3,2,6,5,0,3], k = 2', output: '7' },
    ],
    difficulty: 'hard',
    estMin: 35,
    tags: ['sliding-window', 'dynamic-programming'],
    hints: ['DP: dp[i][j] = max profit using at most j transactions in first i prices.', 'dp[i][j] = max(dp[i-1][j], max over m<i of (prices[i]-prices[m]+dp[m][j-1])).', 'If k >= n/2, unlimited transactions allowed.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Byte Stream Decompressor',
    prompt: 'Given compressed string like `"3[a]2[bc]"`, decode it. The format is `k[encoded_string]` — repeat `encoded_string` exactly `k` times. Brackets can be nested.',
    constraints: '1 ≤ s.length ≤ 30\n1 ≤ k ≤ 300\nLetters only, no extra spaces',
    examples: [
      { input: 's = "3[a]2[bc]"', output: '"aaabcbc"' },
      { input: 's = "2[abc]3[cd]ef"', output: '"abcabccdcdcdef"' },
    ],
    difficulty: 'medium',
    estMin: 25,
    tags: ['sliding-window', 'stack', 'string'],
    hints: ['Use a stack.', 'Push current string and multiplier when `[` found.', 'On `]`, pop and repeat current string, append to restored outer string.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Maximum Erasure Score',
    prompt: 'Given array `nums`, find the **maximum sum** of a subarray with **all distinct elements**.',
    constraints: '1 ≤ nums.length ≤ 10^5\n1 ≤ nums[i] ≤ 10^4',
    examples: [
      { input: 'nums = [4,2,4,5,6]', output: '17', explanation: '[2,4,5,6]' },
      { input: 'nums = [5,2,1,2,5,2,1,2,5]', output: '8' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['sliding-window', 'hash-map'],
    hints: ['Variable window with distinct elements.', 'Track current window sum and a set of elements.', 'Shrink left until no duplicates when expanding right.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Grid Row Cleaner',
    prompt: 'Given 2D binary grid and integer `k`, for each row find the **maximum number of `1`s** obtainable by flipping at most `k` zeros in that row. Return array of answers.',
    constraints: '1 ≤ grid.length, grid[0].length ≤ 1000\ngrid[i][j] ∈ {0, 1}\n0 ≤ k ≤ grid[0].length',
    examples: [
      { input: 'grid = [[0,0,1,1],[1,0,0,1]], k = 1', output: '[3,3]' },
      { input: 'grid = [[1,1,1]], k = 0', output: '[3]' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['sliding-window', 'matrix'],
    hints: ['For each row independently, apply sliding window with at most k zeros.', 'Standard longest ones with k flips.', 'Apply per row.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Minimum Operations Window',
    prompt: 'Given array `nums` and integer `k`, find the **minimum number of increments/decrements** needed to make all elements in some window of size `k` equal.',
    constraints: '1 ≤ k ≤ nums.length ≤ 10^5\n1 ≤ nums[i] ≤ 10^9',
    examples: [
      { input: 'nums = [1,2,3,4,5], k = 3', output: '2', explanation: 'Window [2,3,4] or [1,2,3] both need 2 ops' },
      { input: 'nums = [9,2,9], k = 3', output: '14' },
    ],
    difficulty: 'hard',
    estMin: 30,
    tags: ['sliding-window', 'sorting', 'median'],
    hints: ['Optimal target for a window is the **median**.', 'Cost = sum of |nums[i] - median|.', 'Use sliding window with sorted structure or segment tree for O(n log n).'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Bandwidth Allocation Tracker',
    prompt: 'Given array `bandwidth` of n servers and integer `k`, find the **k consecutive servers** with the **minimum total bandwidth** (to identify bottlenecks).',
    constraints: '1 ≤ k ≤ bandwidth.length ≤ 10^5\n1 ≤ bandwidth[i] ≤ 10^9',
    examples: [
      { input: 'bandwidth = [5,3,8,1,4,2], k = 3', output: '7', explanation: '[1,4,2]=7' },
      { input: 'bandwidth = [10,10,10], k = 2', output: '20' },
    ],
    difficulty: 'easy',
    estMin: 8,
    tags: ['sliding-window', 'fixed-window'],
    hints: ['Fixed window of size k.', 'Slide and track minimum window sum.', 'Return start index or just the sum as asked.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Consecutive Character Compressor',
    prompt: 'Given string `s`, return the **length** of the longest substring that can be obtained after replacing at most `k` characters such that all characters are the same.',
    constraints: '1 ≤ s.length ≤ 10^5\n0 ≤ k ≤ s.length\ns contains uppercase letters',
    examples: [
      { input: 's = "ABAB", k = 2', output: '4' },
      { input: 's = "AABABBA", k = 1', output: '4' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['sliding-window', 'hash-map'],
    hints: ['Track max frequency of any character in current window.', 'Window valid if (window_size - max_freq) <= k.', 'Never shrink window smaller than answer seen so far.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Contiguous Subarray with Bounded Max',
    prompt: 'Given integer array `nums` and bounds `[lo, hi]`, count the number of subarrays where the **maximum element** is between `lo` and `hi` (inclusive).',
    constraints: '1 ≤ nums.length ≤ 10^5\n0 ≤ lo ≤ hi ≤ 10^9\n0 ≤ nums[i] ≤ 10^9',
    examples: [
      { input: 'nums = [2,1,4,3], lo = 2, hi = 3', output: '3' },
      { input: 'nums = [2,9,2,5,6], lo = 2, hi = 8', output: '7' },
    ],
    difficulty: 'medium',
    estMin: 25,
    tags: ['sliding-window', 'counting'],
    hints: ['Track last index where element > hi (resets the count).', 'Track last index where element is in [lo, hi].', 'Each position contributes (lastValid - lastReset) subarrays.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Longest Turbulent Subarray',
    prompt: 'A subarray is **turbulent** if comparisons alternate: A[i] < A[i+1] > A[i+2] < A[i+3]... Find the length of the longest turbulent subarray.',
    constraints: '1 ≤ arr.length ≤ 4×10^4\n0 ≤ arr[i] ≤ 10^9',
    examples: [
      { input: 'arr = [9,4,2,10,7,8,8,1,9]', output: '5', explanation: '[4,2,10,7,8]' },
      { input: 'arr = [4,8,12,16]', output: '2' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['sliding-window'],
    hints: ['Track direction of consecutive comparison (>, <, =).', 'Window breaks when direction does not alternate or equals appear.', 'Extend or reset based on whether current pair continues alternation.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Max Consecutive Ones III',
    prompt: 'Given binary array `nums` and integer `k`, return the **maximum number of consecutive `1`s** if you flip at most `k` `0`s.',
    constraints: '1 ≤ nums.length ≤ 10^5\nnums[i] ∈ {0, 1}\n0 ≤ k ≤ nums.length',
    examples: [
      { input: 'nums = [1,1,1,0,0,0,1,1,1,1,0], k = 2', output: '6' },
      { input: 'nums = [0,0,1,1,0,0,1,1,1,0,1,1,0,0,0,1,1,1,1], k = 3', output: '10' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['sliding-window'],
    hints: ['Sliding window tracking zero count.', 'Expand right; shrink left when zeros > k.', 'Track maximum window size.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Subarray Sum to Goal',
    prompt: 'Given **positive** integer array `nums` and integer `target`, find the **minimum length** of a contiguous subarray with sum **≥ target**. Return 0 if none.',
    constraints: '1 ≤ nums.length ≤ 2×10^5\n1 ≤ target ≤ 10^9\n1 ≤ nums[i] ≤ 10^4',
    examples: [
      { input: 'nums = [2,3,1,2,4,3], target = 7', output: '2' },
      { input: 'nums = [1,4,4], target = 4', output: '1' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['sliding-window'],
    hints: ['All-positive array enables shrinking from left when sum >= target.', 'Expand right to accumulate; shrink left while still meeting target.', 'Track minimum length when valid.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Frequency Balanced Window',
    prompt: 'Given string `s`, find the length of the **shortest substring** that contains all distinct characters of `s` at least once.',
    constraints: '1 ≤ s.length ≤ 10^5\ns contains lowercase letters',
    examples: [
      { input: 's = "aabcbcdbca"', output: '4', explanation: '"dbca"' },
      { input: 's = "abc"', output: '3' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['sliding-window', 'hash-map'],
    hints: ['Find distinct character set first.', 'Variable window: expand right, shrink left while all distinct chars covered.', 'Track minimum valid window.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Letter Tile Possibilities',
    prompt: 'Given string `tiles` representing letter tiles, count the number of possible **non-empty sequences** (subsets of tiles in any order). Only the content matters, not which tile was physically chosen.',
    constraints: '1 ≤ tiles.length ≤ 7\ntiles contains uppercase letters',
    examples: [
      { input: 'tiles = "AAB"', output: '8', explanation: 'A, B, AA, AB, BA, AAB, ABA, BAA' },
      { input: 'tiles = "AAABBC"', output: '188' },
    ],
    difficulty: 'hard',
    estMin: 35,
    tags: ['sliding-window', 'backtracking', 'counting'],
    hints: ['Use frequency array of available tiles.', 'Backtrack: for each position, try placing each available letter.', 'Count every non-empty partial arrangement.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Sorted Subarray Count',
    prompt: 'Given integer array `nums`, count the number of subarrays that are **non-decreasing** (sorted).',
    constraints: '1 ≤ nums.length ≤ 10^5\n-10^9 ≤ nums[i] ≤ 10^9',
    examples: [
      { input: 'nums = [1,3,2,4]', output: '6', explanation: '[1],[3],[2],[4],[1,3],[2,4]' },
      { input: 'nums = [1,2,3]', output: '6' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['sliding-window', 'counting'],
    hints: ['Use a sliding window to find maximal sorted runs.', 'For a run of length L, it contributes L*(L+1)/2 subarrays.', 'Walk and detect when sequence breaks.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Binary Flip Cost Minimizer',
    prompt: 'Given binary string `s`, find the **minimum cost** to flip characters so all `0`s precede all `1`s (i.e., the string has the form `0*1*`). Flipping `0→1` costs 1, flipping `1→0` costs 2.',
    constraints: '1 ≤ s.length ≤ 10^5\ns[i] ∈ {"0", "1"}',
    examples: [
      { input: 's = "001"', output: '0', explanation: 'Already valid' },
      { input: 's = "0011000111"', output: '2' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['sliding-window', 'prefix-sum', 'string'],
    hints: ['The cut point divides: left part should be all 0, right part all 1.', 'For each cut position, compute cost: ones on left * 1 + zeros on right * 2... adjust for given costs.', 'Prefix sums of ones and zeros allow O(1) cost per position.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Grid Diagonal Max',
    prompt: 'Given square matrix `grid` of size `n×n` and integer `k`, find the **maximum sum of any k×k submatrix**.',
    constraints: '1 ≤ k ≤ n ≤ 300\n-100 ≤ grid[i][j] ≤ 100',
    examples: [
      { input: 'grid = [[1,2,3],[4,5,6],[7,8,9]], k = 2', output: '28', explanation: '[[4,5],[7,8]]+... = max is 5+6+8+9=28' },
      { input: 'grid = [[1,1],[1,1]], k = 1', output: '1' },
    ],
    difficulty: 'medium',
    estMin: 25,
    tags: ['sliding-window', 'prefix-sum', 'matrix'],
    hints: ['Build 2D prefix sum matrix.', 'Query sum of k×k submatrix in O(1) using 2D prefix sums.', 'Iterate all valid top-left corners.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Warehouse Zone Scanner',
    prompt: 'You are scanning a warehouse. Given array `temp` of temperature readings and threshold `T`, find the **number of valid zones** — contiguous subarrays where **all readings are within T degrees** of the zone average.',
    constraints: '1 ≤ temp.length ≤ 5000\n0 ≤ temp[i] ≤ 10^4\n0 ≤ T ≤ 100',
    examples: [
      { input: 'temp = [1,3,5], T = 2', output: '5', explanation: 'single elements always valid, [1,3]=ok, [3,5]=ok, [1,3,5] avg=3 and max-avg=2=T' },
      { input: 'temp = [1,10], T = 3', output: '2' },
    ],
    difficulty: 'hard',
    estMin: 30,
    tags: ['sliding-window', 'math'],
    hints: ['A zone is valid if max - avg <= T and avg - min <= T, i.e., max - min <= 2*T.', 'This reduces to max - min <= 2*T.', 'Use deque-based sliding window for O(n) check.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Max Vowel String Window',
    prompt: 'Given string `s` and integer `k`, return the **maximum number of vowels** (`a,e,i,o,u`) in any substring of length `k`.',
    constraints: '1 ≤ k ≤ s.length ≤ 10^5\ns contains lowercase letters',
    examples: [
      { input: 's = "abciiidef", k = 3', output: '3', explanation: '"iii"' },
      { input: 's = "aeiou", k = 2', output: '2' },
    ],
    difficulty: 'easy',
    estMin: 10,
    tags: ['sliding-window', 'string'],
    hints: ['Fixed window of size k.', 'Count vowels entering and leaving window.', 'Track maximum.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Longest Arithmetic Subarray',
    prompt: 'Given integer array `nums`, find the length of the **longest contiguous subarray** that forms an **arithmetic sequence** (constant difference between consecutive elements).',
    constraints: '2 ≤ nums.length ≤ 10^5\n-10^9 ≤ nums[i] ≤ 10^9',
    examples: [
      { input: 'nums = [3,6,9,12]', output: '4' },
      { input: 'nums = [9,4,7,2,10]', output: '3', explanation: '[4,7,10] diff 3' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['sliding-window'],
    hints: ['Walk and track current common difference.', 'When difference changes, reset window start.', 'Track max window length.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The XOR Window Query',
    prompt: 'Given array `nums` and integer `k`, find the **maximum XOR** of any contiguous subarray of length **exactly `k`**.',
    constraints: '1 ≤ k ≤ nums.length ≤ 10^5\n0 ≤ nums[i] ≤ 10^6',
    examples: [
      { input: 'nums = [2,3,5,6,7], k = 2', output: '7', explanation: '2^5=7 or 3^4? XOR of window [2,3]=1,[3,5]=6,[5,6]=3,[6,7]=1. Wait 2^5=7 but [2,5] is not contiguous.' },
      { input: 'nums = [4,8,2,10], k = 2', output: '12', explanation: '4^8=12' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['sliding-window', 'bit-manipulation'],
    hints: ['Maintain XOR of current k-element window.', 'Slide: XOR in new right element, XOR out leftmost element (XOR is self-inverse).', 'Track maximum.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Sparse Signal Finder',
    prompt: 'Given binary array `signal`, find the **minimum distance** between any two `1`s. Return `-1` if fewer than two `1`s exist.',
    constraints: '2 ≤ signal.length ≤ 10^5\nsignal[i] ∈ {0, 1}',
    examples: [
      { input: 'signal = [0,1,0,0,1,0,1]', output: '2' },
      { input: 'signal = [1,0,0,0,1]', output: '4' },
    ],
    difficulty: 'easy',
    estMin: 8,
    tags: ['sliding-window', 'array'],
    hints: ['Track last seen 1 position.', 'When a new 1 is found, compute distance to last 1.', 'Track minimum distance.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Consecutive Increment Builder',
    prompt: 'Given integer array `nums` and integer `k`, find the **maximum sum** achievable by taking elements from a subarray of size `k` after optionally **sorting** that subarray.',
    constraints: '1 ≤ k ≤ nums.length ≤ 10^5\n1 ≤ nums[i] ≤ 10^4',
    examples: [
      { input: 'nums = [2,4,3,1,5], k = 3', output: '12', explanation: 'Best window is [3,4,5]... wait those not contiguous. Best contiguous of size k = sorted window sum is just sum.' },
      { input: 'nums = [10,1,3,5], k = 2', output: '11' },
    ],
    difficulty: 'easy',
    estMin: 8,
    tags: ['sliding-window', 'fixed-window'],
    hints: ['Sorting a subarray just gives its sum unchanged.', 'The maximum sum is simply the maximum sum of any k-element contiguous subarray.', 'Standard fixed window sum maximization.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Segment Tree Range Max',
    prompt: 'Given array `nums` and list of queries `[l, r]`, answer each query: what is the **maximum element** in `nums[l..r]`? Return array of answers.',
    constraints: '1 ≤ nums.length ≤ 3×10^4\n1 ≤ queries.length ≤ 3×10^4\n0 ≤ l ≤ r < nums.length',
    examples: [
      { input: 'nums = [3,1,4,1,5,9,2,6], queries = [[0,3],[2,7]]', output: '[4,9]' },
      { input: 'nums = [7,2,3], queries = [[0,2]]', output: '[7]' },
    ],
    difficulty: 'hard',
    estMin: 35,
    tags: ['sliding-window', 'segment-tree', 'sparse-table'],
    hints: ['Build a sparse table for O(1) range max queries.', 'sparse[i][j] = max of 2^j elements starting at i.', 'Query: use largest power of 2 fitting in range and overlap if needed.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Repeated Subsequence Window',
    prompt: 'Given string `s` and integer `k`, find the number of **distinct substrings of length `k`**.',
    constraints: '1 ≤ k ≤ s.length ≤ 3×10^4',
    examples: [
      { input: 's = "aabaab", k = 2', output: '3', explanation: '"aa","ab","ba"' },
      { input: 's = "abcd", k = 2', output: '3' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['sliding-window', 'hash-map', 'rolling-hash'],
    hints: ['Fixed window of size k.', 'Use a hash set to track unique substrings.', 'Rolling hash or direct string hashing.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Weighted Interval Optimizer',
    prompt: 'Given array `vals` and window size `k`, compute a **score** for each window: sum of `vals[i] * (position_within_window + 1)`. Return the maximum score across all windows.',
    constraints: '1 ≤ k ≤ vals.length ≤ 10^4\n1 ≤ vals[i] ≤ 100',
    examples: [
      { input: 'vals = [1,3,1,2,4], k = 3', output: '20', explanation: 'Window [1,2,4]: 1*1+2*2+4*3=1+4+12=17. Window [3,1,2]: 3+2+6=11. Window [1,3,1]: 1+6+3=10. Max [3,1,2]=11, [1,2,4]=17. Answer 17?' },
      { input: 'vals = [2,3,1,4], k = 2', output: '11', explanation: '[3,1]:3+2=5,[1,4]:1+8=9,[2,3]:2+6=8,[3,1]:3+2=5 → max is [1,4]=9?' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['sliding-window', 'math'],
    hints: ['Compute initial window score for first k elements.', 'For each slide, adjust score: shift all weights (adding new element at weight k, removing element at weight 1).', 'Track cumulative sum to update in O(1).'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Streak Interruption Counter',
    prompt: 'Given binary array `bits`, find the **number of subarrays** that contain **at least one `0`**.',
    constraints: '1 ≤ bits.length ≤ 10^5\nbits[i] ∈ {0, 1}',
    examples: [
      { input: 'bits = [1,0,1,1]', output: '5', explanation: 'Total subarrays = 10; all-1 subarrays = 5; answer = 10-5 = 5' },
      { input: 'bits = [0,0]', output: '3' },
    ],
    difficulty: 'easy',
    estMin: 10,
    tags: ['sliding-window', 'counting', 'complement'],
    hints: ['Total subarrays = n*(n+1)/2.', 'Subtract count of all-1 subarrays.', 'Count all-1 runs and apply triangular sum formula.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Twin Prime Window Scanner',
    prompt: 'Given array `nums`, find the length of the **longest subarray** where every element is a **prime number**.',
    constraints: '1 ≤ nums.length ≤ 10^5\n1 ≤ nums[i] ≤ 10^6',
    examples: [
      { input: 'nums = [2,3,5,4,7,11]', output: '3', explanation: '[2,3,5] then break at 4' },
      { input: 'nums = [4,6,8]', output: '0' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['sliding-window', 'sieve', 'number-theory'],
    hints: ['Precompute primes up to max(nums) with Sieve of Eratosthenes.', 'Walk window: extend while prime, reset on non-prime.', 'Track max length.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Diagonal Stripe Finder',
    prompt: 'Given n×n binary matrix and integer `k`, find the number of k×k submatrices that are **entirely 1s**.',
    constraints: '1 ≤ k ≤ n ≤ 300\nmatrix[i][j] ∈ {0, 1}',
    examples: [
      { input: 'matrix = [[1,1,1],[1,1,1],[1,1,1]], k = 2', output: '4' },
      { input: 'matrix = [[1,0],[0,1]], k = 1', output: '2' },
    ],
    difficulty: 'hard',
    estMin: 30,
    tags: ['sliding-window', 'prefix-sum', 'matrix'],
    hints: ['2D prefix sum for O(1) submatrix sum query.', 'Check if sum of k×k submatrix equals k*k.', 'Iterate all valid top-left corners.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Monotone Increasing Digits Window',
    prompt: 'Given integer `n`, find the **largest number ≤ n** whose digits are **monotonically non-decreasing**.',
    constraints: '0 ≤ n ≤ 10^9',
    examples: [
      { input: 'n = 332', output: '299' },
      { input: 'n = 1234', output: '1234' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['sliding-window', 'greedy', 'string'],
    hints: ['Convert to string of digits.', 'Find rightmost position where digits[i] > digits[i+1].', 'Decrement digits[i] and set all digits after to 9.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Multi-Source Path Smoother',
    prompt: 'Given array `heights` of terrain elevations, find the **minimum cost path** from index 0 to n-1 where cost is the sum of absolute differences between consecutive chosen points, visiting exactly `k` intermediate stops.',
    constraints: '2 ≤ heights.length ≤ 1000\n1 ≤ k < heights.length\n1 ≤ heights[i] ≤ 10^4',
    examples: [
      { input: 'heights = [1,2,3,4,5], k = 2', output: '4', explanation: 'Stops: 0,2,4 → |1-3|+|3-5|=2+2=4' },
      { input: 'heights = [1,100,1,1,1], k = 1', output: '2' },
    ],
    difficulty: 'hard',
    estMin: 35,
    tags: ['sliding-window', 'dynamic-programming'],
    hints: ['DP: dp[i][j] = min cost to reach index i using j stops.', 'Transition: dp[i][j] = min over all m < i of dp[m][j-1] + |heights[m]-heights[i]|.', 'O(n^2 * k) time.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Prefix Average Monitor',
    prompt: 'Given array `data`, for each index `i` return the **floor average** of `data[0..i]`. Return the resulting array.',
    constraints: '1 ≤ data.length ≤ 10^4\n0 ≤ data[i] ≤ 10^4',
    examples: [
      { input: 'data = [1,2,3,4,5]', output: '[1,1,2,2,3]' },
      { input: 'data = [10,0,5]', output: '[10,5,5]' },
    ],
    difficulty: 'easy',
    estMin: 8,
    tags: ['sliding-window', 'prefix-sum'],
    hints: ['Maintain running sum.', 'Divide by i+1 at each step.', 'Single pass.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Unique Character Scrambler',
    prompt: 'Given string `s`, find the **smallest window** (by length) that contains at least one of each unique character in `s`. Return its length.',
    constraints: '1 ≤ s.length ≤ 10^5\ns contains lowercase letters',
    examples: [
      { input: 's = "aabc"', output: '3', explanation: '"abc" or "abc"' },
      { input: 's = "abcabc"', output: '3' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['sliding-window', 'hash-map'],
    hints: ['Compute required char set.', 'Variable window: shrink left while all unique chars still covered.', 'Minimum valid window length.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Sum Pair Difference Window',
    prompt: 'Given array `nums`, find the number of pairs `(i, j)` with `i < j` such that the **absolute difference** of their sums with some prefix is within a range — specifically count subarrays with sum in range `[lo, hi]`.',
    constraints: '1 ≤ nums.length ≤ 10^5\n-10^4 ≤ nums[i] ≤ 10^4\n-10^9 ≤ lo ≤ hi ≤ 10^9',
    examples: [
      { input: 'nums = [-2,5,-1], lo = -2, hi = 2', output: '3' },
      { input: 'nums = [0], lo = 0, hi = 0', output: '1' },
    ],
    difficulty: 'hard',
    estMin: 35,
    tags: ['sliding-window', 'merge-sort', 'prefix-sum'],
    hints: ['Build prefix sum array.', 'Count pairs (i,j) where lo <= prefix[j] - prefix[i] <= hi.', 'Use merge sort to count valid pairs in O(n log n).'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Balanced Bracket Window',
    prompt: 'Given string of brackets `s`, find the **number of substrings** that are valid bracket sequences.',
    constraints: '1 ≤ s.length ≤ 3×10^4\ns[i] ∈ {"(", ")"}',
    examples: [
      { input: 's = "()()"', output: '4', explanation: '"()","()","()()","()()" — 2+1+1=... let me recount: "()" at 0, "()" at 2, "()()" whole = 3 valid? Actually "()()" has (),(),(()?) No: positions [0,1],[2,3],[0,3] = 3' },
      { input: 's = "(())"', output: '2', explanation: '"(())" and "()"' },
    ],
    difficulty: 'medium',
    estMin: 25,
    tags: ['sliding-window', 'stack', 'counting'],
    hints: ['Use stack storing indices.', 'When matching pair found, the number of valid sequences ending here = 1 + index difference to previous stack top.', 'Maintain a base index for reset.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Minimum Flip Equalizer',
    prompt: 'Given binary string `s`, find the minimum number of **flips** to make all characters the same (either all `0` or all `1`).',
    constraints: '1 ≤ s.length ≤ 10^5\ns[i] ∈ {"0", "1"}',
    examples: [
      { input: 's = "010"', output: '1', explanation: 'Flip the middle 1 or either 0' },
      { input: 's = "1111"', output: '0' },
    ],
    difficulty: 'easy',
    estMin: 5,
    tags: ['sliding-window', 'string', 'greedy'],
    hints: ['Count zeros and ones.', 'Min flips = min(count_zeros, count_ones).', 'One pass to count.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Contiguous Range Extender',
    prompt: 'Given array of integers, find the **minimum number of elements to add** so that the array contains every integer in the range `[1, max(nums)]` at least once.',
    constraints: '1 ≤ nums.length ≤ 10^4\n1 ≤ nums[i] ≤ 10^8',
    examples: [
      { input: 'nums = [1,2,3,8]', output: '4', explanation: 'Missing 4,5,6,7' },
      { input: 'nums = [1,5,7]', output: '4' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['sliding-window', 'sorting', 'greedy'],
    hints: ['Sort and deduplicate.', 'Sliding window: count gaps between consecutive distinct values.', 'Sum of (next - curr - 1) for all consecutive pairs.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Score Window Leveler',
    prompt: 'Given array `scores` and integer `k`, for each index `i` the **neighborhood score** is the sum of scores of indices within distance `k` (including itself). Find the index with the **maximum neighborhood score**. Return its index.',
    constraints: '1 ≤ scores.length ≤ 10^5\n1 ≤ k < scores.length\n1 ≤ scores[i] ≤ 10^4',
    examples: [
      { input: 'scores = [1,3,5,2,4], k = 1', output: '2', explanation: 'scores[2] neighborhood: 3+5+2=10' },
      { input: 'scores = [10,2,3], k = 1', output: '0', explanation: '10+2=12 vs 10+2+3=15 vs 2+3=5 → index 1? 0: 10+2=12, 1: 10+2+3=15, 2: 2+3=5 → index 1' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['sliding-window', 'prefix-sum'],
    hints: ['Prefix sum allows O(1) range sum.', 'For each center i, sum = prefix[min(n,i+k+1)] - prefix[max(0,i-k)].', 'Find maximum.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Zero-Sum Fragment Detector',
    prompt: 'Given integer array `nums`, find all **contiguous subarrays with sum zero**. Return count.',
    constraints: '1 ≤ nums.length ≤ 10^4\n-10^4 ≤ nums[i] ≤ 10^4',
    examples: [
      { input: 'nums = [1,-1,1,-1]', output: '4' },
      { input: 'nums = [0,0,0]', output: '6' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['sliding-window', 'hash-map', 'prefix-sum'],
    hints: ['Prefix sum approach: subarray [i+1,j] has zero sum iff prefix[i]==prefix[j].', 'Count pairs of equal prefix sums.', 'Use hash map: for each prefix sum, C(count, 2) pairs.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Max Absolute Sum Subarray',
    prompt: 'Given integer array `nums`, find the **maximum absolute sum** of any subarray — i.e., max of (maximum subarray sum) and (|minimum subarray sum|).',
    constraints: '1 ≤ nums.length ≤ 10^5\n-10^4 ≤ nums[i] ≤ 10^4',
    examples: [
      { input: 'nums = [1,-3,2,3,-4]', output: '5', explanation: 'max subarray sum = [2,3]=5' },
      { input: 'nums = [2,-5,1,-4,3,-2]', output: '8', explanation: 'min subarray = [-5+1-4]=-8, |−8|=8' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['sliding-window', 'dynamic-programming'],
    hints: ["Run Kadane's for max subarray sum.", "Run Kadane's on negated array for max of |min| subarray sum.", 'Return max of both.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Longest Subarray with Bounded Count',
    prompt: 'Given integer array `nums` and integers `a`, `b`, find the length of the **longest subarray** containing at most `a` copies of some designated value `x` and at most `b` copies of value `y`.',
    constraints: '1 ≤ nums.length ≤ 10^5\n0 ≤ a, b ≤ 10^5',
    examples: [
      { input: 'nums = [1,2,1,2,1], x = 1, y = 2, a = 2, b = 1', output: '4', explanation: '[2,1,2,1] has 2 ones and 1 two — wait that has 2 ones which = a. Check [1,2,1,2]: 2 ones, 2 twos — b=1 violated. [2,1,2,1]: 2 ones, 2 twos — violated. [1,2,1]: 2 ones, 1 two = valid, len 3.' },
      { input: 'nums = [1,1,1], x = 1, y = 2, a = 2, b = 1', output: '2' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['sliding-window', 'hash-map'],
    hints: ['Variable window tracking counts of x and y.', 'Shrink left when count(x) > a or count(y) > b.', 'Track maximum valid window.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The K-Sized Group Ranker',
    prompt: 'Given array `nums` and integer `k`, for each window of size `k` find the **rank** of the window (index in sorted order of all window sums). Return array of ranks (1-indexed).',
    constraints: '1 ≤ k ≤ nums.length ≤ 1000\n-100 ≤ nums[i] ≤ 100',
    examples: [
      { input: 'nums = [1,2,3,4], k = 2', output: '[1,2,3]', explanation: 'sums [3,5,7] → ranks [1,2,3]' },
      { input: 'nums = [3,1,2], k = 2', output: '[2,1]', explanation: 'sums [4,3] → sorted [3,4] → ranks [2,1]' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['sliding-window', 'sorting'],
    hints: ['Compute all window sums first.', 'Sort window sums and build rank mapping.', 'Map each window sum to its rank.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Minimum Subarray Flip',
    prompt: 'Given binary array `nums`, find the **minimum number of adjacent swaps** to group all `1`s together. Return this count.',
    constraints: '1 ≤ nums.length ≤ 10^5\nnums[i] ∈ {0, 1}',
    examples: [
      { input: 'nums = [1,0,1,0,1]', output: '2' },
      { input: 'nums = [0,0,0,1,0]', output: '0' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['sliding-window', 'greedy', 'prefix-sum'],
    hints: ['Collect positions of all 1s.', 'Best grouping puts them together around their median position.', 'Sliding window on positions of 1s: cost = sum of |pos[i] - target_i|, minimized at median.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Range Frequency Counter',
    prompt: 'Given array `nums` and queries `[left, right, value]`, for each query return the **frequency of `value`** in `nums[left..right]`.',
    constraints: '1 ≤ nums.length ≤ 10^4\n1 ≤ queries.length ≤ 10^4\n1 ≤ nums[i], value ≤ 10^4',
    examples: [
      { input: 'nums = [1,1,2,1,1], queries = [[0,4,1],[1,3,2]]', output: '[4,1]' },
      { input: 'nums = [2,2,2], queries = [[0,2,2]]', output: '[3]' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['sliding-window', 'hash-map', 'binary-search'],
    hints: ['Pre-build map from value → sorted list of its positions.', 'For each query, binary search to count positions in [left, right].', 'O((n + q) log n) total.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Tiling Window Pattern',
    prompt: 'Given array `pattern` of length `m` and array `nums` of length `n`, find all starting indices in `nums` where **a window of length `m` has the same relative order pattern** (same comparison result between consecutive elements) as `pattern`.',
    constraints: '1 ≤ m ≤ n ≤ 10^5\n-10^9 ≤ nums[i], pattern[i] ≤ 10^9',
    examples: [
      { input: 'nums = [1,2,3,4,5,6], pattern = [1,1]', output: '[0,1,2,3,4]', explanation: 'any two consecutive elements are increasing' },
      { input: 'nums = [1,4,2,5,3], pattern = [-1,1]', output: '[1,3]' },
    ],
    difficulty: 'medium',
    estMin: 25,
    tags: ['sliding-window', 'string-matching'],
    hints: ['Convert nums and pattern to sign arrays (1, 0, -1 for <, =, >).', 'Fixed window of size m in sign(nums).', 'Match sign windows against sign(pattern).'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Longest Nice Subarray',
    prompt: 'Given positive integer array `nums`, find the length of the **longest subarray** where the **bitwise AND of any two elements is 0** (no two elements share a set bit).',
    constraints: '1 ≤ nums.length ≤ 10^5\n1 ≤ nums[i] ≤ 10^9',
    examples: [
      { input: 'nums = [1,3,8,48,10]', output: '3', explanation: '[3,8,48]: 3&8=0, 8&48=0, 3&48=0' },
      { input: 'nums = [3,1,5,11,13]', output: '1' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['sliding-window', 'bit-manipulation'],
    hints: ['Use a bitmask of all bits used in current window.', 'When new element shares a bit, shrink left until no conflict.', 'Track max window size.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Delivery Route Optimizer',
    prompt: 'Given array `stops` of distances between consecutive delivery stops and integer `fuel` capacity, find the maximum number of **consecutive stops** you can visit starting from any stop without running out of fuel. Each stop refills one unit.',
    constraints: '1 ≤ stops.length ≤ 10^5\n1 ≤ stops[i] ≤ 10^4\n1 ≤ fuel ≤ 10^9',
    examples: [
      { input: 'stops = [3,2,8,1,4], fuel = 6', output: '3', explanation: 'stops 1-3: 2+8=10>6. stops 3-5: 1+4=5≤6, length 3' },
      { input: 'stops = [1,1,1,1], fuel = 5', output: '4' },
    ],
    difficulty: 'medium',
    estMin: 15,
    tags: ['sliding-window'],
    hints: ['Variable window; track sum of distances in window.', 'Expand right; shrink left when sum > fuel.', 'Track maximum window size.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The GCD Window Maximizer',
    prompt: 'Given integer array `nums` and integer `k`, find the **maximum GCD** of any subarray of length exactly `k`.',
    constraints: '1 ≤ k ≤ nums.length ≤ 10^4\n1 ≤ nums[i] ≤ 10^6',
    examples: [
      { input: 'nums = [2,4,6,8], k = 2', output: '4', explanation: 'gcd(4,8)=4' },
      { input: 'nums = [3,6,9], k = 3', output: '3' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['sliding-window', 'math', 'gcd'],
    hints: ['Fixed window of size k.', 'Compute GCD of window as it slides (cannot do incrementally — recompute from scratch or use segment tree).', 'Sparse table for range GCD queries enables O(n log n).'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Encoded Signal Decoder',
    prompt: 'Given array `freq` of signal frequencies and integer `k`, find the **number of subarrays of length `k`** where the **sum of distinct values** equals the sum of all elements (i.e., all elements are distinct).',
    constraints: '1 ≤ k ≤ freq.length ≤ 10^5\n1 ≤ freq[i] ≤ 10^5',
    examples: [
      { input: 'freq = [1,2,3,4,5], k = 3', output: '3', explanation: 'All windows of size 3 have distinct elements here' },
      { input: 'freq = [1,1,2,3], k = 2', output: '2', explanation: '[1,2] and [2,3] but [1,1] is not' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['sliding-window', 'hash-map', 'fixed-window'],
    hints: ['Fixed window of size k.', 'Track frequency of each value in window.', 'Count windows where all frequencies are 1.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Minimum Adjacent Swaps',
    prompt: 'Given string `s` of `0`s and `1`s, find the **minimum adjacent swaps** to bring all `1`s together in a contiguous block.',
    constraints: '1 ≤ s.length ≤ 10^5\ns[i] ∈ {"0", "1"}',
    examples: [
      { input: 's = "10011"', output: '1' },
      { input: 's = "0111100"', output: '2' },
    ],
    difficulty: 'medium',
    estMin: 20,
    tags: ['sliding-window', 'greedy', 'prefix-sum'],
    hints: ['Collect positions of 1s.', 'Try every window of k ones (k = total count).', 'Cost for a given window = sum|pos[i] - expectedPos[i]|, minimized by shifting to median.'],
  },
  {
    patternSlug: 'sliding-window',
    title: 'The Sensor Coverage Planner',
    prompt: 'Given `n` points on a line and integer `k`, place **k sensors**, each covering range `[x-r, x+r]` centered at some chosen point. Find the **minimum `r`** such that all given points are covered.',
    constraints: '1 ≤ points.length ≤ 10^4\n1 ≤ k ≤ points.length\n-10^9 ≤ points[i] ≤ 10^9',
    examples: [
      { input: 'points = [1,3,6,10], k = 2', output: '2', explanation: 'Sensor at 2 covers [1,3], sensor at 8 covers [6,10]' },
      { input: 'points = [1,5], k = 1', output: '2' },
    ],
    difficulty: 'hard',
    estMin: 30,
    tags: ['sliding-window', 'binary-search', 'greedy'],
    hints: ['Binary search on the answer r.', 'For a given r, greedily check if k sensors suffice: sort points, extend coverage as far as possible.', 'Check feasibility in O(n).'],
  },
]
